// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BlockHeader.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_BlockHeader_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_BlockHeader_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_BlockHeader_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_BlockHeader_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BlockHeader_2eproto;
namespace bcos {
namespace protocol {
class BlockHeaderPB;
class BlockHeaderPBDefaultTypeInternal;
extern BlockHeaderPBDefaultTypeInternal _BlockHeaderPB_default_instance_;
}  // namespace protocol
}  // namespace bcos
PROTOBUF_NAMESPACE_OPEN
template<> ::bcos::protocol::BlockHeaderPB* Arena::CreateMaybeMessage<::bcos::protocol::BlockHeaderPB>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace bcos {
namespace protocol {

// ===================================================================

class BlockHeaderPB PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bcos.protocol.BlockHeaderPB) */ {
 public:
  inline BlockHeaderPB() : BlockHeaderPB(nullptr) {}
  virtual ~BlockHeaderPB();

  BlockHeaderPB(const BlockHeaderPB& from);
  BlockHeaderPB(BlockHeaderPB&& from) noexcept
    : BlockHeaderPB() {
    *this = ::std::move(from);
  }

  inline BlockHeaderPB& operator=(const BlockHeaderPB& from) {
    CopyFrom(from);
    return *this;
  }
  inline BlockHeaderPB& operator=(BlockHeaderPB&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BlockHeaderPB& default_instance();

  static inline const BlockHeaderPB* internal_default_instance() {
    return reinterpret_cast<const BlockHeaderPB*>(
               &_BlockHeaderPB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BlockHeaderPB& a, BlockHeaderPB& b) {
    a.Swap(&b);
  }
  inline void Swap(BlockHeaderPB* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BlockHeaderPB* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BlockHeaderPB* New() const final {
    return CreateMaybeMessage<BlockHeaderPB>(nullptr);
  }

  BlockHeaderPB* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BlockHeaderPB>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BlockHeaderPB& from);
  void MergeFrom(const BlockHeaderPB& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BlockHeaderPB* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bcos.protocol.BlockHeaderPB";
  }
  protected:
  explicit BlockHeaderPB(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_BlockHeader_2eproto);
    return ::descriptor_table_BlockHeader_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParentHashFieldNumber = 2,
    kStateRootFieldNumber = 3,
    kTransactionRootFieldNumber = 4,
    kReceiptRootFieldNumber = 5,
    kDbHashFieldNumber = 6,
    kLogBloomFieldNumber = 7,
    kGasLimitFieldNumber = 9,
    kGasUsedFieldNumber = 10,
    kExtraDataFieldNumber = 12,
    kSealerListFieldNumber = 14,
    kBlockNumberFieldNumber = 8,
    kTimestampFieldNumber = 11,
    kSealerIdxFieldNumber = 13,
    kVersionFieldNumber = 1,
  };
  // bytes parentHash = 2;
  void clear_parenthash();
  const std::string& parenthash() const;
  void set_parenthash(const std::string& value);
  void set_parenthash(std::string&& value);
  void set_parenthash(const char* value);
  void set_parenthash(const void* value, size_t size);
  std::string* mutable_parenthash();
  std::string* release_parenthash();
  void set_allocated_parenthash(std::string* parenthash);
  private:
  const std::string& _internal_parenthash() const;
  void _internal_set_parenthash(const std::string& value);
  std::string* _internal_mutable_parenthash();
  public:

  // bytes stateRoot = 3;
  void clear_stateroot();
  const std::string& stateroot() const;
  void set_stateroot(const std::string& value);
  void set_stateroot(std::string&& value);
  void set_stateroot(const char* value);
  void set_stateroot(const void* value, size_t size);
  std::string* mutable_stateroot();
  std::string* release_stateroot();
  void set_allocated_stateroot(std::string* stateroot);
  private:
  const std::string& _internal_stateroot() const;
  void _internal_set_stateroot(const std::string& value);
  std::string* _internal_mutable_stateroot();
  public:

  // bytes transactionRoot = 4;
  void clear_transactionroot();
  const std::string& transactionroot() const;
  void set_transactionroot(const std::string& value);
  void set_transactionroot(std::string&& value);
  void set_transactionroot(const char* value);
  void set_transactionroot(const void* value, size_t size);
  std::string* mutable_transactionroot();
  std::string* release_transactionroot();
  void set_allocated_transactionroot(std::string* transactionroot);
  private:
  const std::string& _internal_transactionroot() const;
  void _internal_set_transactionroot(const std::string& value);
  std::string* _internal_mutable_transactionroot();
  public:

  // bytes receiptRoot = 5;
  void clear_receiptroot();
  const std::string& receiptroot() const;
  void set_receiptroot(const std::string& value);
  void set_receiptroot(std::string&& value);
  void set_receiptroot(const char* value);
  void set_receiptroot(const void* value, size_t size);
  std::string* mutable_receiptroot();
  std::string* release_receiptroot();
  void set_allocated_receiptroot(std::string* receiptroot);
  private:
  const std::string& _internal_receiptroot() const;
  void _internal_set_receiptroot(const std::string& value);
  std::string* _internal_mutable_receiptroot();
  public:

  // bytes dbHash = 6;
  void clear_dbhash();
  const std::string& dbhash() const;
  void set_dbhash(const std::string& value);
  void set_dbhash(std::string&& value);
  void set_dbhash(const char* value);
  void set_dbhash(const void* value, size_t size);
  std::string* mutable_dbhash();
  std::string* release_dbhash();
  void set_allocated_dbhash(std::string* dbhash);
  private:
  const std::string& _internal_dbhash() const;
  void _internal_set_dbhash(const std::string& value);
  std::string* _internal_mutable_dbhash();
  public:

  // bytes logBloom = 7;
  void clear_logbloom();
  const std::string& logbloom() const;
  void set_logbloom(const std::string& value);
  void set_logbloom(std::string&& value);
  void set_logbloom(const char* value);
  void set_logbloom(const void* value, size_t size);
  std::string* mutable_logbloom();
  std::string* release_logbloom();
  void set_allocated_logbloom(std::string* logbloom);
  private:
  const std::string& _internal_logbloom() const;
  void _internal_set_logbloom(const std::string& value);
  std::string* _internal_mutable_logbloom();
  public:

  // string gasLimit = 9;
  void clear_gaslimit();
  const std::string& gaslimit() const;
  void set_gaslimit(const std::string& value);
  void set_gaslimit(std::string&& value);
  void set_gaslimit(const char* value);
  void set_gaslimit(const char* value, size_t size);
  std::string* mutable_gaslimit();
  std::string* release_gaslimit();
  void set_allocated_gaslimit(std::string* gaslimit);
  private:
  const std::string& _internal_gaslimit() const;
  void _internal_set_gaslimit(const std::string& value);
  std::string* _internal_mutable_gaslimit();
  public:

  // string gasUsed = 10;
  void clear_gasused();
  const std::string& gasused() const;
  void set_gasused(const std::string& value);
  void set_gasused(std::string&& value);
  void set_gasused(const char* value);
  void set_gasused(const char* value, size_t size);
  std::string* mutable_gasused();
  std::string* release_gasused();
  void set_allocated_gasused(std::string* gasused);
  private:
  const std::string& _internal_gasused() const;
  void _internal_set_gasused(const std::string& value);
  std::string* _internal_mutable_gasused();
  public:

  // bytes extraData = 12;
  void clear_extradata();
  const std::string& extradata() const;
  void set_extradata(const std::string& value);
  void set_extradata(std::string&& value);
  void set_extradata(const char* value);
  void set_extradata(const void* value, size_t size);
  std::string* mutable_extradata();
  std::string* release_extradata();
  void set_allocated_extradata(std::string* extradata);
  private:
  const std::string& _internal_extradata() const;
  void _internal_set_extradata(const std::string& value);
  std::string* _internal_mutable_extradata();
  public:

  // bytes sealerList = 14;
  void clear_sealerlist();
  const std::string& sealerlist() const;
  void set_sealerlist(const std::string& value);
  void set_sealerlist(std::string&& value);
  void set_sealerlist(const char* value);
  void set_sealerlist(const void* value, size_t size);
  std::string* mutable_sealerlist();
  std::string* release_sealerlist();
  void set_allocated_sealerlist(std::string* sealerlist);
  private:
  const std::string& _internal_sealerlist() const;
  void _internal_set_sealerlist(const std::string& value);
  std::string* _internal_mutable_sealerlist();
  public:

  // int64 blockNumber = 8;
  void clear_blocknumber();
  ::PROTOBUF_NAMESPACE_ID::int64 blocknumber() const;
  void set_blocknumber(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_blocknumber() const;
  void _internal_set_blocknumber(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 timestamp = 11;
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 sealerIdx = 13;
  void clear_sealeridx();
  ::PROTOBUF_NAMESPACE_ID::int64 sealeridx() const;
  void set_sealeridx(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_sealeridx() const;
  void _internal_set_sealeridx(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 version = 1;
  void clear_version();
  ::PROTOBUF_NAMESPACE_ID::int32 version() const;
  void set_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_version() const;
  void _internal_set_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:bcos.protocol.BlockHeaderPB)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr parenthash_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stateroot_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr transactionroot_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr receiptroot_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dbhash_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr logbloom_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr gaslimit_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr gasused_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr extradata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sealerlist_;
  ::PROTOBUF_NAMESPACE_ID::int64 blocknumber_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::int64 sealeridx_;
  ::PROTOBUF_NAMESPACE_ID::int32 version_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_BlockHeader_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BlockHeaderPB

// int32 version = 1;
inline void BlockHeaderPB::clear_version() {
  version_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 BlockHeaderPB::_internal_version() const {
  return version_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 BlockHeaderPB::version() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockHeaderPB.version)
  return _internal_version();
}
inline void BlockHeaderPB::_internal_set_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  version_ = value;
}
inline void BlockHeaderPB::set_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.BlockHeaderPB.version)
}

// bytes parentHash = 2;
inline void BlockHeaderPB::clear_parenthash() {
  parenthash_.ClearToEmpty();
}
inline const std::string& BlockHeaderPB::parenthash() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockHeaderPB.parentHash)
  return _internal_parenthash();
}
inline void BlockHeaderPB::set_parenthash(const std::string& value) {
  _internal_set_parenthash(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.BlockHeaderPB.parentHash)
}
inline std::string* BlockHeaderPB::mutable_parenthash() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.BlockHeaderPB.parentHash)
  return _internal_mutable_parenthash();
}
inline const std::string& BlockHeaderPB::_internal_parenthash() const {
  return parenthash_.Get();
}
inline void BlockHeaderPB::_internal_set_parenthash(const std::string& value) {
  
  parenthash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void BlockHeaderPB::set_parenthash(std::string&& value) {
  
  parenthash_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.BlockHeaderPB.parentHash)
}
inline void BlockHeaderPB::set_parenthash(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  parenthash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.BlockHeaderPB.parentHash)
}
inline void BlockHeaderPB::set_parenthash(const void* value,
    size_t size) {
  
  parenthash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.BlockHeaderPB.parentHash)
}
inline std::string* BlockHeaderPB::_internal_mutable_parenthash() {
  
  return parenthash_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BlockHeaderPB::release_parenthash() {
  // @@protoc_insertion_point(field_release:bcos.protocol.BlockHeaderPB.parentHash)
  return parenthash_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BlockHeaderPB::set_allocated_parenthash(std::string* parenthash) {
  if (parenthash != nullptr) {
    
  } else {
    
  }
  parenthash_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), parenthash,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.BlockHeaderPB.parentHash)
}

// bytes stateRoot = 3;
inline void BlockHeaderPB::clear_stateroot() {
  stateroot_.ClearToEmpty();
}
inline const std::string& BlockHeaderPB::stateroot() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockHeaderPB.stateRoot)
  return _internal_stateroot();
}
inline void BlockHeaderPB::set_stateroot(const std::string& value) {
  _internal_set_stateroot(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.BlockHeaderPB.stateRoot)
}
inline std::string* BlockHeaderPB::mutable_stateroot() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.BlockHeaderPB.stateRoot)
  return _internal_mutable_stateroot();
}
inline const std::string& BlockHeaderPB::_internal_stateroot() const {
  return stateroot_.Get();
}
inline void BlockHeaderPB::_internal_set_stateroot(const std::string& value) {
  
  stateroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void BlockHeaderPB::set_stateroot(std::string&& value) {
  
  stateroot_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.BlockHeaderPB.stateRoot)
}
inline void BlockHeaderPB::set_stateroot(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  stateroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.BlockHeaderPB.stateRoot)
}
inline void BlockHeaderPB::set_stateroot(const void* value,
    size_t size) {
  
  stateroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.BlockHeaderPB.stateRoot)
}
inline std::string* BlockHeaderPB::_internal_mutable_stateroot() {
  
  return stateroot_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BlockHeaderPB::release_stateroot() {
  // @@protoc_insertion_point(field_release:bcos.protocol.BlockHeaderPB.stateRoot)
  return stateroot_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BlockHeaderPB::set_allocated_stateroot(std::string* stateroot) {
  if (stateroot != nullptr) {
    
  } else {
    
  }
  stateroot_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), stateroot,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.BlockHeaderPB.stateRoot)
}

// bytes transactionRoot = 4;
inline void BlockHeaderPB::clear_transactionroot() {
  transactionroot_.ClearToEmpty();
}
inline const std::string& BlockHeaderPB::transactionroot() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockHeaderPB.transactionRoot)
  return _internal_transactionroot();
}
inline void BlockHeaderPB::set_transactionroot(const std::string& value) {
  _internal_set_transactionroot(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.BlockHeaderPB.transactionRoot)
}
inline std::string* BlockHeaderPB::mutable_transactionroot() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.BlockHeaderPB.transactionRoot)
  return _internal_mutable_transactionroot();
}
inline const std::string& BlockHeaderPB::_internal_transactionroot() const {
  return transactionroot_.Get();
}
inline void BlockHeaderPB::_internal_set_transactionroot(const std::string& value) {
  
  transactionroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void BlockHeaderPB::set_transactionroot(std::string&& value) {
  
  transactionroot_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.BlockHeaderPB.transactionRoot)
}
inline void BlockHeaderPB::set_transactionroot(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  transactionroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.BlockHeaderPB.transactionRoot)
}
inline void BlockHeaderPB::set_transactionroot(const void* value,
    size_t size) {
  
  transactionroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.BlockHeaderPB.transactionRoot)
}
inline std::string* BlockHeaderPB::_internal_mutable_transactionroot() {
  
  return transactionroot_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BlockHeaderPB::release_transactionroot() {
  // @@protoc_insertion_point(field_release:bcos.protocol.BlockHeaderPB.transactionRoot)
  return transactionroot_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BlockHeaderPB::set_allocated_transactionroot(std::string* transactionroot) {
  if (transactionroot != nullptr) {
    
  } else {
    
  }
  transactionroot_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), transactionroot,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.BlockHeaderPB.transactionRoot)
}

// bytes receiptRoot = 5;
inline void BlockHeaderPB::clear_receiptroot() {
  receiptroot_.ClearToEmpty();
}
inline const std::string& BlockHeaderPB::receiptroot() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockHeaderPB.receiptRoot)
  return _internal_receiptroot();
}
inline void BlockHeaderPB::set_receiptroot(const std::string& value) {
  _internal_set_receiptroot(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.BlockHeaderPB.receiptRoot)
}
inline std::string* BlockHeaderPB::mutable_receiptroot() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.BlockHeaderPB.receiptRoot)
  return _internal_mutable_receiptroot();
}
inline const std::string& BlockHeaderPB::_internal_receiptroot() const {
  return receiptroot_.Get();
}
inline void BlockHeaderPB::_internal_set_receiptroot(const std::string& value) {
  
  receiptroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void BlockHeaderPB::set_receiptroot(std::string&& value) {
  
  receiptroot_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.BlockHeaderPB.receiptRoot)
}
inline void BlockHeaderPB::set_receiptroot(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  receiptroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.BlockHeaderPB.receiptRoot)
}
inline void BlockHeaderPB::set_receiptroot(const void* value,
    size_t size) {
  
  receiptroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.BlockHeaderPB.receiptRoot)
}
inline std::string* BlockHeaderPB::_internal_mutable_receiptroot() {
  
  return receiptroot_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BlockHeaderPB::release_receiptroot() {
  // @@protoc_insertion_point(field_release:bcos.protocol.BlockHeaderPB.receiptRoot)
  return receiptroot_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BlockHeaderPB::set_allocated_receiptroot(std::string* receiptroot) {
  if (receiptroot != nullptr) {
    
  } else {
    
  }
  receiptroot_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), receiptroot,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.BlockHeaderPB.receiptRoot)
}

// bytes dbHash = 6;
inline void BlockHeaderPB::clear_dbhash() {
  dbhash_.ClearToEmpty();
}
inline const std::string& BlockHeaderPB::dbhash() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockHeaderPB.dbHash)
  return _internal_dbhash();
}
inline void BlockHeaderPB::set_dbhash(const std::string& value) {
  _internal_set_dbhash(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.BlockHeaderPB.dbHash)
}
inline std::string* BlockHeaderPB::mutable_dbhash() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.BlockHeaderPB.dbHash)
  return _internal_mutable_dbhash();
}
inline const std::string& BlockHeaderPB::_internal_dbhash() const {
  return dbhash_.Get();
}
inline void BlockHeaderPB::_internal_set_dbhash(const std::string& value) {
  
  dbhash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void BlockHeaderPB::set_dbhash(std::string&& value) {
  
  dbhash_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.BlockHeaderPB.dbHash)
}
inline void BlockHeaderPB::set_dbhash(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  dbhash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.BlockHeaderPB.dbHash)
}
inline void BlockHeaderPB::set_dbhash(const void* value,
    size_t size) {
  
  dbhash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.BlockHeaderPB.dbHash)
}
inline std::string* BlockHeaderPB::_internal_mutable_dbhash() {
  
  return dbhash_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BlockHeaderPB::release_dbhash() {
  // @@protoc_insertion_point(field_release:bcos.protocol.BlockHeaderPB.dbHash)
  return dbhash_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BlockHeaderPB::set_allocated_dbhash(std::string* dbhash) {
  if (dbhash != nullptr) {
    
  } else {
    
  }
  dbhash_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), dbhash,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.BlockHeaderPB.dbHash)
}

// bytes logBloom = 7;
inline void BlockHeaderPB::clear_logbloom() {
  logbloom_.ClearToEmpty();
}
inline const std::string& BlockHeaderPB::logbloom() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockHeaderPB.logBloom)
  return _internal_logbloom();
}
inline void BlockHeaderPB::set_logbloom(const std::string& value) {
  _internal_set_logbloom(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.BlockHeaderPB.logBloom)
}
inline std::string* BlockHeaderPB::mutable_logbloom() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.BlockHeaderPB.logBloom)
  return _internal_mutable_logbloom();
}
inline const std::string& BlockHeaderPB::_internal_logbloom() const {
  return logbloom_.Get();
}
inline void BlockHeaderPB::_internal_set_logbloom(const std::string& value) {
  
  logbloom_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void BlockHeaderPB::set_logbloom(std::string&& value) {
  
  logbloom_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.BlockHeaderPB.logBloom)
}
inline void BlockHeaderPB::set_logbloom(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  logbloom_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.BlockHeaderPB.logBloom)
}
inline void BlockHeaderPB::set_logbloom(const void* value,
    size_t size) {
  
  logbloom_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.BlockHeaderPB.logBloom)
}
inline std::string* BlockHeaderPB::_internal_mutable_logbloom() {
  
  return logbloom_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BlockHeaderPB::release_logbloom() {
  // @@protoc_insertion_point(field_release:bcos.protocol.BlockHeaderPB.logBloom)
  return logbloom_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BlockHeaderPB::set_allocated_logbloom(std::string* logbloom) {
  if (logbloom != nullptr) {
    
  } else {
    
  }
  logbloom_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), logbloom,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.BlockHeaderPB.logBloom)
}

// int64 blockNumber = 8;
inline void BlockHeaderPB::clear_blocknumber() {
  blocknumber_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 BlockHeaderPB::_internal_blocknumber() const {
  return blocknumber_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 BlockHeaderPB::blocknumber() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockHeaderPB.blockNumber)
  return _internal_blocknumber();
}
inline void BlockHeaderPB::_internal_set_blocknumber(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  blocknumber_ = value;
}
inline void BlockHeaderPB::set_blocknumber(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_blocknumber(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.BlockHeaderPB.blockNumber)
}

// string gasLimit = 9;
inline void BlockHeaderPB::clear_gaslimit() {
  gaslimit_.ClearToEmpty();
}
inline const std::string& BlockHeaderPB::gaslimit() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockHeaderPB.gasLimit)
  return _internal_gaslimit();
}
inline void BlockHeaderPB::set_gaslimit(const std::string& value) {
  _internal_set_gaslimit(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.BlockHeaderPB.gasLimit)
}
inline std::string* BlockHeaderPB::mutable_gaslimit() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.BlockHeaderPB.gasLimit)
  return _internal_mutable_gaslimit();
}
inline const std::string& BlockHeaderPB::_internal_gaslimit() const {
  return gaslimit_.Get();
}
inline void BlockHeaderPB::_internal_set_gaslimit(const std::string& value) {
  
  gaslimit_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void BlockHeaderPB::set_gaslimit(std::string&& value) {
  
  gaslimit_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.BlockHeaderPB.gasLimit)
}
inline void BlockHeaderPB::set_gaslimit(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  gaslimit_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.BlockHeaderPB.gasLimit)
}
inline void BlockHeaderPB::set_gaslimit(const char* value,
    size_t size) {
  
  gaslimit_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.BlockHeaderPB.gasLimit)
}
inline std::string* BlockHeaderPB::_internal_mutable_gaslimit() {
  
  return gaslimit_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BlockHeaderPB::release_gaslimit() {
  // @@protoc_insertion_point(field_release:bcos.protocol.BlockHeaderPB.gasLimit)
  return gaslimit_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BlockHeaderPB::set_allocated_gaslimit(std::string* gaslimit) {
  if (gaslimit != nullptr) {
    
  } else {
    
  }
  gaslimit_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), gaslimit,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.BlockHeaderPB.gasLimit)
}

// string gasUsed = 10;
inline void BlockHeaderPB::clear_gasused() {
  gasused_.ClearToEmpty();
}
inline const std::string& BlockHeaderPB::gasused() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockHeaderPB.gasUsed)
  return _internal_gasused();
}
inline void BlockHeaderPB::set_gasused(const std::string& value) {
  _internal_set_gasused(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.BlockHeaderPB.gasUsed)
}
inline std::string* BlockHeaderPB::mutable_gasused() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.BlockHeaderPB.gasUsed)
  return _internal_mutable_gasused();
}
inline const std::string& BlockHeaderPB::_internal_gasused() const {
  return gasused_.Get();
}
inline void BlockHeaderPB::_internal_set_gasused(const std::string& value) {
  
  gasused_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void BlockHeaderPB::set_gasused(std::string&& value) {
  
  gasused_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.BlockHeaderPB.gasUsed)
}
inline void BlockHeaderPB::set_gasused(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  gasused_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.BlockHeaderPB.gasUsed)
}
inline void BlockHeaderPB::set_gasused(const char* value,
    size_t size) {
  
  gasused_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.BlockHeaderPB.gasUsed)
}
inline std::string* BlockHeaderPB::_internal_mutable_gasused() {
  
  return gasused_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BlockHeaderPB::release_gasused() {
  // @@protoc_insertion_point(field_release:bcos.protocol.BlockHeaderPB.gasUsed)
  return gasused_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BlockHeaderPB::set_allocated_gasused(std::string* gasused) {
  if (gasused != nullptr) {
    
  } else {
    
  }
  gasused_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), gasused,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.BlockHeaderPB.gasUsed)
}

// int64 timestamp = 11;
inline void BlockHeaderPB::clear_timestamp() {
  timestamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 BlockHeaderPB::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 BlockHeaderPB::timestamp() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockHeaderPB.timestamp)
  return _internal_timestamp();
}
inline void BlockHeaderPB::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  timestamp_ = value;
}
inline void BlockHeaderPB::set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.BlockHeaderPB.timestamp)
}

// bytes extraData = 12;
inline void BlockHeaderPB::clear_extradata() {
  extradata_.ClearToEmpty();
}
inline const std::string& BlockHeaderPB::extradata() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockHeaderPB.extraData)
  return _internal_extradata();
}
inline void BlockHeaderPB::set_extradata(const std::string& value) {
  _internal_set_extradata(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.BlockHeaderPB.extraData)
}
inline std::string* BlockHeaderPB::mutable_extradata() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.BlockHeaderPB.extraData)
  return _internal_mutable_extradata();
}
inline const std::string& BlockHeaderPB::_internal_extradata() const {
  return extradata_.Get();
}
inline void BlockHeaderPB::_internal_set_extradata(const std::string& value) {
  
  extradata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void BlockHeaderPB::set_extradata(std::string&& value) {
  
  extradata_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.BlockHeaderPB.extraData)
}
inline void BlockHeaderPB::set_extradata(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  extradata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.BlockHeaderPB.extraData)
}
inline void BlockHeaderPB::set_extradata(const void* value,
    size_t size) {
  
  extradata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.BlockHeaderPB.extraData)
}
inline std::string* BlockHeaderPB::_internal_mutable_extradata() {
  
  return extradata_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BlockHeaderPB::release_extradata() {
  // @@protoc_insertion_point(field_release:bcos.protocol.BlockHeaderPB.extraData)
  return extradata_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BlockHeaderPB::set_allocated_extradata(std::string* extradata) {
  if (extradata != nullptr) {
    
  } else {
    
  }
  extradata_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), extradata,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.BlockHeaderPB.extraData)
}

// int64 sealerIdx = 13;
inline void BlockHeaderPB::clear_sealeridx() {
  sealeridx_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 BlockHeaderPB::_internal_sealeridx() const {
  return sealeridx_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 BlockHeaderPB::sealeridx() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockHeaderPB.sealerIdx)
  return _internal_sealeridx();
}
inline void BlockHeaderPB::_internal_set_sealeridx(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  sealeridx_ = value;
}
inline void BlockHeaderPB::set_sealeridx(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_sealeridx(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.BlockHeaderPB.sealerIdx)
}

// bytes sealerList = 14;
inline void BlockHeaderPB::clear_sealerlist() {
  sealerlist_.ClearToEmpty();
}
inline const std::string& BlockHeaderPB::sealerlist() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockHeaderPB.sealerList)
  return _internal_sealerlist();
}
inline void BlockHeaderPB::set_sealerlist(const std::string& value) {
  _internal_set_sealerlist(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.BlockHeaderPB.sealerList)
}
inline std::string* BlockHeaderPB::mutable_sealerlist() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.BlockHeaderPB.sealerList)
  return _internal_mutable_sealerlist();
}
inline const std::string& BlockHeaderPB::_internal_sealerlist() const {
  return sealerlist_.Get();
}
inline void BlockHeaderPB::_internal_set_sealerlist(const std::string& value) {
  
  sealerlist_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void BlockHeaderPB::set_sealerlist(std::string&& value) {
  
  sealerlist_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.BlockHeaderPB.sealerList)
}
inline void BlockHeaderPB::set_sealerlist(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sealerlist_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.BlockHeaderPB.sealerList)
}
inline void BlockHeaderPB::set_sealerlist(const void* value,
    size_t size) {
  
  sealerlist_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.BlockHeaderPB.sealerList)
}
inline std::string* BlockHeaderPB::_internal_mutable_sealerlist() {
  
  return sealerlist_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BlockHeaderPB::release_sealerlist() {
  // @@protoc_insertion_point(field_release:bcos.protocol.BlockHeaderPB.sealerList)
  return sealerlist_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BlockHeaderPB::set_allocated_sealerlist(std::string* sealerlist) {
  if (sealerlist != nullptr) {
    
  } else {
    
  }
  sealerlist_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sealerlist,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.BlockHeaderPB.sealerList)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace bcos

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_BlockHeader_2eproto
