// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BlockHeader.proto

#include "BlockHeader.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace bcos {
namespace protocol {
class BlockHeaderPBDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<BlockHeaderPB> _instance;
} _BlockHeaderPB_default_instance_;
}  // namespace protocol
}  // namespace bcos
static void InitDefaultsscc_info_BlockHeaderPB_BlockHeader_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bcos::protocol::_BlockHeaderPB_default_instance_;
    new (ptr) ::bcos::protocol::BlockHeaderPB();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_BlockHeaderPB_BlockHeader_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_BlockHeaderPB_BlockHeader_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_BlockHeader_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_BlockHeader_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_BlockHeader_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_BlockHeader_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, version_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, parenthash_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, stateroot_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, transactionroot_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, receiptroot_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, dbhash_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, logbloom_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, blocknumber_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, gaslimit_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, gasused_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, timestamp_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, extradata_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, sealeridx_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::BlockHeaderPB, sealerlist_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::bcos::protocol::BlockHeaderPB)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bcos::protocol::_BlockHeaderPB_default_instance_),
};

const char descriptor_table_protodef_BlockHeader_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021BlockHeader.proto\022\rbcos.protocol\"\234\002\n\rB"
  "lockHeaderPB\022\017\n\007version\030\001 \001(\005\022\022\n\nparentH"
  "ash\030\002 \001(\014\022\021\n\tstateRoot\030\003 \001(\014\022\027\n\017transact"
  "ionRoot\030\004 \001(\014\022\023\n\013receiptRoot\030\005 \001(\014\022\016\n\006db"
  "Hash\030\006 \001(\014\022\020\n\010logBloom\030\007 \001(\014\022\023\n\013blockNum"
  "ber\030\010 \001(\003\022\020\n\010gasLimit\030\t \001(\t\022\017\n\007gasUsed\030\n"
  " \001(\t\022\021\n\ttimestamp\030\013 \001(\003\022\021\n\textraData\030\014 \001"
  "(\014\022\021\n\tsealerIdx\030\r \001(\003\022\022\n\nsealerList\030\016 \001("
  "\014b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_BlockHeader_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_BlockHeader_2eproto_sccs[1] = {
  &scc_info_BlockHeaderPB_BlockHeader_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_BlockHeader_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BlockHeader_2eproto = {
  false, false, descriptor_table_protodef_BlockHeader_2eproto, "BlockHeader.proto", 329,
  &descriptor_table_BlockHeader_2eproto_once, descriptor_table_BlockHeader_2eproto_sccs, descriptor_table_BlockHeader_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_BlockHeader_2eproto::offsets,
  file_level_metadata_BlockHeader_2eproto, 1, file_level_enum_descriptors_BlockHeader_2eproto, file_level_service_descriptors_BlockHeader_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_BlockHeader_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_BlockHeader_2eproto)), true);
namespace bcos {
namespace protocol {

// ===================================================================

class BlockHeaderPB::_Internal {
 public:
};

BlockHeaderPB::BlockHeaderPB(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:bcos.protocol.BlockHeaderPB)
}
BlockHeaderPB::BlockHeaderPB(const BlockHeaderPB& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  parenthash_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_parenthash().empty()) {
    parenthash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_parenthash(), 
      GetArena());
  }
  stateroot_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_stateroot().empty()) {
    stateroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_stateroot(), 
      GetArena());
  }
  transactionroot_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_transactionroot().empty()) {
    transactionroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_transactionroot(), 
      GetArena());
  }
  receiptroot_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_receiptroot().empty()) {
    receiptroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_receiptroot(), 
      GetArena());
  }
  dbhash_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_dbhash().empty()) {
    dbhash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_dbhash(), 
      GetArena());
  }
  logbloom_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_logbloom().empty()) {
    logbloom_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_logbloom(), 
      GetArena());
  }
  gaslimit_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_gaslimit().empty()) {
    gaslimit_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_gaslimit(), 
      GetArena());
  }
  gasused_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_gasused().empty()) {
    gasused_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_gasused(), 
      GetArena());
  }
  extradata_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_extradata().empty()) {
    extradata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_extradata(), 
      GetArena());
  }
  sealerlist_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sealerlist().empty()) {
    sealerlist_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sealerlist(), 
      GetArena());
  }
  ::memcpy(&blocknumber_, &from.blocknumber_,
    static_cast<size_t>(reinterpret_cast<char*>(&version_) -
    reinterpret_cast<char*>(&blocknumber_)) + sizeof(version_));
  // @@protoc_insertion_point(copy_constructor:bcos.protocol.BlockHeaderPB)
}

void BlockHeaderPB::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_BlockHeaderPB_BlockHeader_2eproto.base);
  parenthash_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  stateroot_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  transactionroot_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  receiptroot_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  dbhash_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  logbloom_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  gaslimit_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  gasused_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  extradata_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  sealerlist_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&blocknumber_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&version_) -
      reinterpret_cast<char*>(&blocknumber_)) + sizeof(version_));
}

BlockHeaderPB::~BlockHeaderPB() {
  // @@protoc_insertion_point(destructor:bcos.protocol.BlockHeaderPB)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void BlockHeaderPB::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  parenthash_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  stateroot_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  transactionroot_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  receiptroot_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  dbhash_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  logbloom_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  gaslimit_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  gasused_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  extradata_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  sealerlist_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void BlockHeaderPB::ArenaDtor(void* object) {
  BlockHeaderPB* _this = reinterpret_cast< BlockHeaderPB* >(object);
  (void)_this;
}
void BlockHeaderPB::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void BlockHeaderPB::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const BlockHeaderPB& BlockHeaderPB::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_BlockHeaderPB_BlockHeader_2eproto.base);
  return *internal_default_instance();
}


void BlockHeaderPB::Clear() {
// @@protoc_insertion_point(message_clear_start:bcos.protocol.BlockHeaderPB)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  parenthash_.ClearToEmpty();
  stateroot_.ClearToEmpty();
  transactionroot_.ClearToEmpty();
  receiptroot_.ClearToEmpty();
  dbhash_.ClearToEmpty();
  logbloom_.ClearToEmpty();
  gaslimit_.ClearToEmpty();
  gasused_.ClearToEmpty();
  extradata_.ClearToEmpty();
  sealerlist_.ClearToEmpty();
  ::memset(&blocknumber_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&version_) -
      reinterpret_cast<char*>(&blocknumber_)) + sizeof(version_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BlockHeaderPB::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 version = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes parentHash = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_parenthash();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes stateRoot = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_stateroot();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes transactionRoot = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_transactionroot();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes receiptRoot = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_receiptroot();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes dbHash = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_dbhash();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes logBloom = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          auto str = _internal_mutable_logbloom();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 blockNumber = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          blocknumber_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string gasLimit = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          auto str = _internal_mutable_gaslimit();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "bcos.protocol.BlockHeaderPB.gasLimit"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string gasUsed = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          auto str = _internal_mutable_gasused();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "bcos.protocol.BlockHeaderPB.gasUsed"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 timestamp = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 88)) {
          timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes extraData = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 98)) {
          auto str = _internal_mutable_extradata();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 sealerIdx = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 104)) {
          sealeridx_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes sealerList = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 114)) {
          auto str = _internal_mutable_sealerlist();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* BlockHeaderPB::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bcos.protocol.BlockHeaderPB)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 version = 1;
  if (this->version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_version(), target);
  }

  // bytes parentHash = 2;
  if (this->parenthash().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_parenthash(), target);
  }

  // bytes stateRoot = 3;
  if (this->stateroot().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_stateroot(), target);
  }

  // bytes transactionRoot = 4;
  if (this->transactionroot().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_transactionroot(), target);
  }

  // bytes receiptRoot = 5;
  if (this->receiptroot().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_receiptroot(), target);
  }

  // bytes dbHash = 6;
  if (this->dbhash().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        6, this->_internal_dbhash(), target);
  }

  // bytes logBloom = 7;
  if (this->logbloom().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        7, this->_internal_logbloom(), target);
  }

  // int64 blockNumber = 8;
  if (this->blocknumber() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(8, this->_internal_blocknumber(), target);
  }

  // string gasLimit = 9;
  if (this->gaslimit().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_gaslimit().data(), static_cast<int>(this->_internal_gaslimit().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bcos.protocol.BlockHeaderPB.gasLimit");
    target = stream->WriteStringMaybeAliased(
        9, this->_internal_gaslimit(), target);
  }

  // string gasUsed = 10;
  if (this->gasused().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_gasused().data(), static_cast<int>(this->_internal_gasused().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bcos.protocol.BlockHeaderPB.gasUsed");
    target = stream->WriteStringMaybeAliased(
        10, this->_internal_gasused(), target);
  }

  // int64 timestamp = 11;
  if (this->timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(11, this->_internal_timestamp(), target);
  }

  // bytes extraData = 12;
  if (this->extradata().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        12, this->_internal_extradata(), target);
  }

  // int64 sealerIdx = 13;
  if (this->sealeridx() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(13, this->_internal_sealeridx(), target);
  }

  // bytes sealerList = 14;
  if (this->sealerlist().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        14, this->_internal_sealerlist(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bcos.protocol.BlockHeaderPB)
  return target;
}

size_t BlockHeaderPB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bcos.protocol.BlockHeaderPB)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes parentHash = 2;
  if (this->parenthash().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_parenthash());
  }

  // bytes stateRoot = 3;
  if (this->stateroot().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_stateroot());
  }

  // bytes transactionRoot = 4;
  if (this->transactionroot().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_transactionroot());
  }

  // bytes receiptRoot = 5;
  if (this->receiptroot().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_receiptroot());
  }

  // bytes dbHash = 6;
  if (this->dbhash().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_dbhash());
  }

  // bytes logBloom = 7;
  if (this->logbloom().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_logbloom());
  }

  // string gasLimit = 9;
  if (this->gaslimit().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_gaslimit());
  }

  // string gasUsed = 10;
  if (this->gasused().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_gasused());
  }

  // bytes extraData = 12;
  if (this->extradata().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_extradata());
  }

  // bytes sealerList = 14;
  if (this->sealerlist().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_sealerlist());
  }

  // int64 blockNumber = 8;
  if (this->blocknumber() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_blocknumber());
  }

  // int64 timestamp = 11;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_timestamp());
  }

  // int64 sealerIdx = 13;
  if (this->sealeridx() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_sealeridx());
  }

  // int32 version = 1;
  if (this->version() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_version());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BlockHeaderPB::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bcos.protocol.BlockHeaderPB)
  GOOGLE_DCHECK_NE(&from, this);
  const BlockHeaderPB* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<BlockHeaderPB>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bcos.protocol.BlockHeaderPB)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bcos.protocol.BlockHeaderPB)
    MergeFrom(*source);
  }
}

void BlockHeaderPB::MergeFrom(const BlockHeaderPB& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bcos.protocol.BlockHeaderPB)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.parenthash().size() > 0) {
    _internal_set_parenthash(from._internal_parenthash());
  }
  if (from.stateroot().size() > 0) {
    _internal_set_stateroot(from._internal_stateroot());
  }
  if (from.transactionroot().size() > 0) {
    _internal_set_transactionroot(from._internal_transactionroot());
  }
  if (from.receiptroot().size() > 0) {
    _internal_set_receiptroot(from._internal_receiptroot());
  }
  if (from.dbhash().size() > 0) {
    _internal_set_dbhash(from._internal_dbhash());
  }
  if (from.logbloom().size() > 0) {
    _internal_set_logbloom(from._internal_logbloom());
  }
  if (from.gaslimit().size() > 0) {
    _internal_set_gaslimit(from._internal_gaslimit());
  }
  if (from.gasused().size() > 0) {
    _internal_set_gasused(from._internal_gasused());
  }
  if (from.extradata().size() > 0) {
    _internal_set_extradata(from._internal_extradata());
  }
  if (from.sealerlist().size() > 0) {
    _internal_set_sealerlist(from._internal_sealerlist());
  }
  if (from.blocknumber() != 0) {
    _internal_set_blocknumber(from._internal_blocknumber());
  }
  if (from.timestamp() != 0) {
    _internal_set_timestamp(from._internal_timestamp());
  }
  if (from.sealeridx() != 0) {
    _internal_set_sealeridx(from._internal_sealeridx());
  }
  if (from.version() != 0) {
    _internal_set_version(from._internal_version());
  }
}

void BlockHeaderPB::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bcos.protocol.BlockHeaderPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BlockHeaderPB::CopyFrom(const BlockHeaderPB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bcos.protocol.BlockHeaderPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BlockHeaderPB::IsInitialized() const {
  return true;
}

void BlockHeaderPB::InternalSwap(BlockHeaderPB* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  parenthash_.Swap(&other->parenthash_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  stateroot_.Swap(&other->stateroot_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  transactionroot_.Swap(&other->transactionroot_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  receiptroot_.Swap(&other->receiptroot_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  dbhash_.Swap(&other->dbhash_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  logbloom_.Swap(&other->logbloom_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  gaslimit_.Swap(&other->gaslimit_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  gasused_.Swap(&other->gasused_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  extradata_.Swap(&other->extradata_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  sealerlist_.Swap(&other->sealerlist_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BlockHeaderPB, version_)
      + sizeof(BlockHeaderPB::version_)
      - PROTOBUF_FIELD_OFFSET(BlockHeaderPB, blocknumber_)>(
          reinterpret_cast<char*>(&blocknumber_),
          reinterpret_cast<char*>(&other->blocknumber_));
}

::PROTOBUF_NAMESPACE_ID::Metadata BlockHeaderPB::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace bcos
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::bcos::protocol::BlockHeaderPB* Arena::CreateMaybeMessage< ::bcos::protocol::BlockHeaderPB >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bcos::protocol::BlockHeaderPB >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
