// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Block.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Block_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Block_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "BlockHeader.pb.h"
#include "Transaction.pb.h"
#include "TransactionReceipt.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Block_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Block_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Block_2eproto;
namespace bcos {
namespace protocol {
class BlockPB;
class BlockPBDefaultTypeInternal;
extern BlockPBDefaultTypeInternal _BlockPB_default_instance_;
}  // namespace protocol
}  // namespace bcos
PROTOBUF_NAMESPACE_OPEN
template<> ::bcos::protocol::BlockPB* Arena::CreateMaybeMessage<::bcos::protocol::BlockPB>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace bcos {
namespace protocol {

// ===================================================================

class BlockPB PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bcos.protocol.BlockPB) */ {
 public:
  inline BlockPB() : BlockPB(nullptr) {}
  virtual ~BlockPB();

  BlockPB(const BlockPB& from);
  BlockPB(BlockPB&& from) noexcept
    : BlockPB() {
    *this = ::std::move(from);
  }

  inline BlockPB& operator=(const BlockPB& from) {
    CopyFrom(from);
    return *this;
  }
  inline BlockPB& operator=(BlockPB&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BlockPB& default_instance();

  static inline const BlockPB* internal_default_instance() {
    return reinterpret_cast<const BlockPB*>(
               &_BlockPB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BlockPB& a, BlockPB& b) {
    a.Swap(&b);
  }
  inline void Swap(BlockPB* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BlockPB* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BlockPB* New() const final {
    return CreateMaybeMessage<BlockPB>(nullptr);
  }

  BlockPB* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BlockPB>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BlockPB& from);
  void MergeFrom(const BlockPB& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BlockPB* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bcos.protocol.BlockPB";
  }
  protected:
  explicit BlockPB(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Block_2eproto);
    return ::descriptor_table_Block_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransactionsFieldNumber = 2,
    kTransactionReceiptsFieldNumber = 3,
    kSignatureListFieldNumber = 4,
    kBlockHeaderFieldNumber = 1,
  };
  // repeated .bcos.protocol.TransactionPB transactions = 2;
  int transactions_size() const;
  private:
  int _internal_transactions_size() const;
  public:
  void clear_transactions();
  ::bcos::protocol::TransactionPB* mutable_transactions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::TransactionPB >*
      mutable_transactions();
  private:
  const ::bcos::protocol::TransactionPB& _internal_transactions(int index) const;
  ::bcos::protocol::TransactionPB* _internal_add_transactions();
  public:
  const ::bcos::protocol::TransactionPB& transactions(int index) const;
  ::bcos::protocol::TransactionPB* add_transactions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::TransactionPB >&
      transactions() const;

  // repeated .bcos.protocol.TransactionReceiptPB TransactionReceipts = 3;
  int transactionreceipts_size() const;
  private:
  int _internal_transactionreceipts_size() const;
  public:
  void clear_transactionreceipts();
  ::bcos::protocol::TransactionReceiptPB* mutable_transactionreceipts(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::TransactionReceiptPB >*
      mutable_transactionreceipts();
  private:
  const ::bcos::protocol::TransactionReceiptPB& _internal_transactionreceipts(int index) const;
  ::bcos::protocol::TransactionReceiptPB* _internal_add_transactionreceipts();
  public:
  const ::bcos::protocol::TransactionReceiptPB& transactionreceipts(int index) const;
  ::bcos::protocol::TransactionReceiptPB* add_transactionreceipts();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::TransactionReceiptPB >&
      transactionreceipts() const;

  // repeated .bcos.protocol.SignaturePB signatureList = 4;
  int signaturelist_size() const;
  private:
  int _internal_signaturelist_size() const;
  public:
  void clear_signaturelist();
  ::bcos::protocol::SignaturePB* mutable_signaturelist(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::SignaturePB >*
      mutable_signaturelist();
  private:
  const ::bcos::protocol::SignaturePB& _internal_signaturelist(int index) const;
  ::bcos::protocol::SignaturePB* _internal_add_signaturelist();
  public:
  const ::bcos::protocol::SignaturePB& signaturelist(int index) const;
  ::bcos::protocol::SignaturePB* add_signaturelist();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::SignaturePB >&
      signaturelist() const;

  // .bcos.protocol.BlockHeaderPB blockHeader = 1;
  bool has_blockheader() const;
  private:
  bool _internal_has_blockheader() const;
  public:
  void clear_blockheader();
  const ::bcos::protocol::BlockHeaderPB& blockheader() const;
  ::bcos::protocol::BlockHeaderPB* release_blockheader();
  ::bcos::protocol::BlockHeaderPB* mutable_blockheader();
  void set_allocated_blockheader(::bcos::protocol::BlockHeaderPB* blockheader);
  private:
  const ::bcos::protocol::BlockHeaderPB& _internal_blockheader() const;
  ::bcos::protocol::BlockHeaderPB* _internal_mutable_blockheader();
  public:
  void unsafe_arena_set_allocated_blockheader(
      ::bcos::protocol::BlockHeaderPB* blockheader);
  ::bcos::protocol::BlockHeaderPB* unsafe_arena_release_blockheader();

  // @@protoc_insertion_point(class_scope:bcos.protocol.BlockPB)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::TransactionPB > transactions_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::TransactionReceiptPB > transactionreceipts_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::SignaturePB > signaturelist_;
  ::bcos::protocol::BlockHeaderPB* blockheader_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Block_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BlockPB

// .bcos.protocol.BlockHeaderPB blockHeader = 1;
inline bool BlockPB::_internal_has_blockheader() const {
  return this != internal_default_instance() && blockheader_ != nullptr;
}
inline bool BlockPB::has_blockheader() const {
  return _internal_has_blockheader();
}
inline const ::bcos::protocol::BlockHeaderPB& BlockPB::_internal_blockheader() const {
  const ::bcos::protocol::BlockHeaderPB* p = blockheader_;
  return p != nullptr ? *p : reinterpret_cast<const ::bcos::protocol::BlockHeaderPB&>(
      ::bcos::protocol::_BlockHeaderPB_default_instance_);
}
inline const ::bcos::protocol::BlockHeaderPB& BlockPB::blockheader() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockPB.blockHeader)
  return _internal_blockheader();
}
inline void BlockPB::unsafe_arena_set_allocated_blockheader(
    ::bcos::protocol::BlockHeaderPB* blockheader) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(blockheader_);
  }
  blockheader_ = blockheader;
  if (blockheader) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:bcos.protocol.BlockPB.blockHeader)
}
inline ::bcos::protocol::BlockHeaderPB* BlockPB::release_blockheader() {
  
  ::bcos::protocol::BlockHeaderPB* temp = blockheader_;
  blockheader_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::bcos::protocol::BlockHeaderPB* BlockPB::unsafe_arena_release_blockheader() {
  // @@protoc_insertion_point(field_release:bcos.protocol.BlockPB.blockHeader)
  
  ::bcos::protocol::BlockHeaderPB* temp = blockheader_;
  blockheader_ = nullptr;
  return temp;
}
inline ::bcos::protocol::BlockHeaderPB* BlockPB::_internal_mutable_blockheader() {
  
  if (blockheader_ == nullptr) {
    auto* p = CreateMaybeMessage<::bcos::protocol::BlockHeaderPB>(GetArena());
    blockheader_ = p;
  }
  return blockheader_;
}
inline ::bcos::protocol::BlockHeaderPB* BlockPB::mutable_blockheader() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.BlockPB.blockHeader)
  return _internal_mutable_blockheader();
}
inline void BlockPB::set_allocated_blockheader(::bcos::protocol::BlockHeaderPB* blockheader) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(blockheader_);
  }
  if (blockheader) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(blockheader)->GetArena();
    if (message_arena != submessage_arena) {
      blockheader = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, blockheader, submessage_arena);
    }
    
  } else {
    
  }
  blockheader_ = blockheader;
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.BlockPB.blockHeader)
}

// repeated .bcos.protocol.TransactionPB transactions = 2;
inline int BlockPB::_internal_transactions_size() const {
  return transactions_.size();
}
inline int BlockPB::transactions_size() const {
  return _internal_transactions_size();
}
inline ::bcos::protocol::TransactionPB* BlockPB::mutable_transactions(int index) {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.BlockPB.transactions)
  return transactions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::TransactionPB >*
BlockPB::mutable_transactions() {
  // @@protoc_insertion_point(field_mutable_list:bcos.protocol.BlockPB.transactions)
  return &transactions_;
}
inline const ::bcos::protocol::TransactionPB& BlockPB::_internal_transactions(int index) const {
  return transactions_.Get(index);
}
inline const ::bcos::protocol::TransactionPB& BlockPB::transactions(int index) const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockPB.transactions)
  return _internal_transactions(index);
}
inline ::bcos::protocol::TransactionPB* BlockPB::_internal_add_transactions() {
  return transactions_.Add();
}
inline ::bcos::protocol::TransactionPB* BlockPB::add_transactions() {
  // @@protoc_insertion_point(field_add:bcos.protocol.BlockPB.transactions)
  return _internal_add_transactions();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::TransactionPB >&
BlockPB::transactions() const {
  // @@protoc_insertion_point(field_list:bcos.protocol.BlockPB.transactions)
  return transactions_;
}

// repeated .bcos.protocol.TransactionReceiptPB TransactionReceipts = 3;
inline int BlockPB::_internal_transactionreceipts_size() const {
  return transactionreceipts_.size();
}
inline int BlockPB::transactionreceipts_size() const {
  return _internal_transactionreceipts_size();
}
inline ::bcos::protocol::TransactionReceiptPB* BlockPB::mutable_transactionreceipts(int index) {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.BlockPB.TransactionReceipts)
  return transactionreceipts_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::TransactionReceiptPB >*
BlockPB::mutable_transactionreceipts() {
  // @@protoc_insertion_point(field_mutable_list:bcos.protocol.BlockPB.TransactionReceipts)
  return &transactionreceipts_;
}
inline const ::bcos::protocol::TransactionReceiptPB& BlockPB::_internal_transactionreceipts(int index) const {
  return transactionreceipts_.Get(index);
}
inline const ::bcos::protocol::TransactionReceiptPB& BlockPB::transactionreceipts(int index) const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockPB.TransactionReceipts)
  return _internal_transactionreceipts(index);
}
inline ::bcos::protocol::TransactionReceiptPB* BlockPB::_internal_add_transactionreceipts() {
  return transactionreceipts_.Add();
}
inline ::bcos::protocol::TransactionReceiptPB* BlockPB::add_transactionreceipts() {
  // @@protoc_insertion_point(field_add:bcos.protocol.BlockPB.TransactionReceipts)
  return _internal_add_transactionreceipts();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::TransactionReceiptPB >&
BlockPB::transactionreceipts() const {
  // @@protoc_insertion_point(field_list:bcos.protocol.BlockPB.TransactionReceipts)
  return transactionreceipts_;
}

// repeated .bcos.protocol.SignaturePB signatureList = 4;
inline int BlockPB::_internal_signaturelist_size() const {
  return signaturelist_.size();
}
inline int BlockPB::signaturelist_size() const {
  return _internal_signaturelist_size();
}
inline ::bcos::protocol::SignaturePB* BlockPB::mutable_signaturelist(int index) {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.BlockPB.signatureList)
  return signaturelist_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::SignaturePB >*
BlockPB::mutable_signaturelist() {
  // @@protoc_insertion_point(field_mutable_list:bcos.protocol.BlockPB.signatureList)
  return &signaturelist_;
}
inline const ::bcos::protocol::SignaturePB& BlockPB::_internal_signaturelist(int index) const {
  return signaturelist_.Get(index);
}
inline const ::bcos::protocol::SignaturePB& BlockPB::signaturelist(int index) const {
  // @@protoc_insertion_point(field_get:bcos.protocol.BlockPB.signatureList)
  return _internal_signaturelist(index);
}
inline ::bcos::protocol::SignaturePB* BlockPB::_internal_add_signaturelist() {
  return signaturelist_.Add();
}
inline ::bcos::protocol::SignaturePB* BlockPB::add_signaturelist() {
  // @@protoc_insertion_point(field_add:bcos.protocol.BlockPB.signatureList)
  return _internal_add_signaturelist();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bcos::protocol::SignaturePB >&
BlockPB::signaturelist() const {
  // @@protoc_insertion_point(field_list:bcos.protocol.BlockPB.signatureList)
  return signaturelist_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace bcos

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Block_2eproto
