// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParallelBlock.proto

#include "ParallelBlock.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_BlockHeader_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_BlockHeaderPB_BlockHeader_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_Transaction_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SignaturePB_Transaction_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_TransactionReceipt_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_TransactionReceiptPB_TransactionReceipt_2eproto;
namespace bcos {
namespace protocol {
class ParallelBlockPBDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ParallelBlockPB> _instance;
} _ParallelBlockPB_default_instance_;
}  // namespace protocol
}  // namespace bcos
static void InitDefaultsscc_info_ParallelBlockPB_ParallelBlock_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bcos::protocol::_ParallelBlockPB_default_instance_;
    new (ptr) ::bcos::protocol::ParallelBlockPB();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_ParallelBlockPB_ParallelBlock_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 3, 0, InitDefaultsscc_info_ParallelBlockPB_ParallelBlock_2eproto}, {
      &scc_info_BlockHeaderPB_BlockHeader_2eproto.base,
      &scc_info_TransactionReceiptPB_TransactionReceipt_2eproto.base,
      &scc_info_SignaturePB_Transaction_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_ParallelBlock_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_ParallelBlock_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ParallelBlock_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_ParallelBlock_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::ParallelBlockPB, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::ParallelBlockPB, blockheader_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::ParallelBlockPB, transactions_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::ParallelBlockPB, transactionreceipts_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::ParallelBlockPB, signaturelist_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::bcos::protocol::ParallelBlockPB)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bcos::protocol::_ParallelBlockPB_default_instance_),
};

const char descriptor_table_protodef_ParallelBlock_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023ParallelBlock.proto\022\rbcos.protocol\032\021Bl"
  "ockHeader.proto\032\021Transaction.proto\032\030Tran"
  "sactionReceipt.proto\"\317\001\n\017ParallelBlockPB"
  "\0221\n\013blockHeader\030\001 \001(\0132\034.bcos.protocol.Bl"
  "ockHeaderPB\022\024\n\014transactions\030\002 \003(\014\022@\n\023Tra"
  "nsactionReceipts\030\003 \003(\0132#.bcos.protocol.T"
  "ransactionReceiptPB\0221\n\rsignatureList\030\004 \003"
  "(\0132\032.bcos.protocol.SignaturePBb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_ParallelBlock_2eproto_deps[3] = {
  &::descriptor_table_BlockHeader_2eproto,
  &::descriptor_table_Transaction_2eproto,
  &::descriptor_table_TransactionReceipt_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_ParallelBlock_2eproto_sccs[1] = {
  &scc_info_ParallelBlockPB_ParallelBlock_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ParallelBlock_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ParallelBlock_2eproto = {
  false, false, descriptor_table_protodef_ParallelBlock_2eproto, "ParallelBlock.proto", 318,
  &descriptor_table_ParallelBlock_2eproto_once, descriptor_table_ParallelBlock_2eproto_sccs, descriptor_table_ParallelBlock_2eproto_deps, 1, 3,
  schemas, file_default_instances, TableStruct_ParallelBlock_2eproto::offsets,
  file_level_metadata_ParallelBlock_2eproto, 1, file_level_enum_descriptors_ParallelBlock_2eproto, file_level_service_descriptors_ParallelBlock_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_ParallelBlock_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_ParallelBlock_2eproto)), true);
namespace bcos {
namespace protocol {

// ===================================================================

class ParallelBlockPB::_Internal {
 public:
  static const ::bcos::protocol::BlockHeaderPB& blockheader(const ParallelBlockPB* msg);
};

const ::bcos::protocol::BlockHeaderPB&
ParallelBlockPB::_Internal::blockheader(const ParallelBlockPB* msg) {
  return *msg->blockheader_;
}
void ParallelBlockPB::clear_blockheader() {
  if (GetArena() == nullptr && blockheader_ != nullptr) {
    delete blockheader_;
  }
  blockheader_ = nullptr;
}
void ParallelBlockPB::clear_transactionreceipts() {
  transactionreceipts_.Clear();
}
void ParallelBlockPB::clear_signaturelist() {
  signaturelist_.Clear();
}
ParallelBlockPB::ParallelBlockPB(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  transactions_(arena),
  transactionreceipts_(arena),
  signaturelist_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:bcos.protocol.ParallelBlockPB)
}
ParallelBlockPB::ParallelBlockPB(const ParallelBlockPB& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      transactions_(from.transactions_),
      transactionreceipts_(from.transactionreceipts_),
      signaturelist_(from.signaturelist_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_blockheader()) {
    blockheader_ = new ::bcos::protocol::BlockHeaderPB(*from.blockheader_);
  } else {
    blockheader_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:bcos.protocol.ParallelBlockPB)
}

void ParallelBlockPB::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ParallelBlockPB_ParallelBlock_2eproto.base);
  blockheader_ = nullptr;
}

ParallelBlockPB::~ParallelBlockPB() {
  // @@protoc_insertion_point(destructor:bcos.protocol.ParallelBlockPB)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ParallelBlockPB::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete blockheader_;
}

void ParallelBlockPB::ArenaDtor(void* object) {
  ParallelBlockPB* _this = reinterpret_cast< ParallelBlockPB* >(object);
  (void)_this;
}
void ParallelBlockPB::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ParallelBlockPB::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ParallelBlockPB& ParallelBlockPB::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ParallelBlockPB_ParallelBlock_2eproto.base);
  return *internal_default_instance();
}


void ParallelBlockPB::Clear() {
// @@protoc_insertion_point(message_clear_start:bcos.protocol.ParallelBlockPB)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  transactions_.Clear();
  transactionreceipts_.Clear();
  signaturelist_.Clear();
  if (GetArena() == nullptr && blockheader_ != nullptr) {
    delete blockheader_;
  }
  blockheader_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ParallelBlockPB::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .bcos.protocol.BlockHeaderPB blockHeader = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_blockheader(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated bytes transactions = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_transactions();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .bcos.protocol.TransactionReceiptPB TransactionReceipts = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_transactionreceipts(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .bcos.protocol.SignaturePB signatureList = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_signaturelist(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ParallelBlockPB::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bcos.protocol.ParallelBlockPB)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .bcos.protocol.BlockHeaderPB blockHeader = 1;
  if (this->has_blockheader()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::blockheader(this), target, stream);
  }

  // repeated bytes transactions = 2;
  for (int i = 0, n = this->_internal_transactions_size(); i < n; i++) {
    const auto& s = this->_internal_transactions(i);
    target = stream->WriteBytes(2, s, target);
  }

  // repeated .bcos.protocol.TransactionReceiptPB TransactionReceipts = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_transactionreceipts_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_transactionreceipts(i), target, stream);
  }

  // repeated .bcos.protocol.SignaturePB signatureList = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_signaturelist_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_signaturelist(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bcos.protocol.ParallelBlockPB)
  return target;
}

size_t ParallelBlockPB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bcos.protocol.ParallelBlockPB)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated bytes transactions = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(transactions_.size());
  for (int i = 0, n = transactions_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
      transactions_.Get(i));
  }

  // repeated .bcos.protocol.TransactionReceiptPB TransactionReceipts = 3;
  total_size += 1UL * this->_internal_transactionreceipts_size();
  for (const auto& msg : this->transactionreceipts_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .bcos.protocol.SignaturePB signatureList = 4;
  total_size += 1UL * this->_internal_signaturelist_size();
  for (const auto& msg : this->signaturelist_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .bcos.protocol.BlockHeaderPB blockHeader = 1;
  if (this->has_blockheader()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *blockheader_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ParallelBlockPB::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bcos.protocol.ParallelBlockPB)
  GOOGLE_DCHECK_NE(&from, this);
  const ParallelBlockPB* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ParallelBlockPB>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bcos.protocol.ParallelBlockPB)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bcos.protocol.ParallelBlockPB)
    MergeFrom(*source);
  }
}

void ParallelBlockPB::MergeFrom(const ParallelBlockPB& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bcos.protocol.ParallelBlockPB)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  transactions_.MergeFrom(from.transactions_);
  transactionreceipts_.MergeFrom(from.transactionreceipts_);
  signaturelist_.MergeFrom(from.signaturelist_);
  if (from.has_blockheader()) {
    _internal_mutable_blockheader()->::bcos::protocol::BlockHeaderPB::MergeFrom(from._internal_blockheader());
  }
}

void ParallelBlockPB::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bcos.protocol.ParallelBlockPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParallelBlockPB::CopyFrom(const ParallelBlockPB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bcos.protocol.ParallelBlockPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParallelBlockPB::IsInitialized() const {
  return true;
}

void ParallelBlockPB::InternalSwap(ParallelBlockPB* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  transactions_.InternalSwap(&other->transactions_);
  transactionreceipts_.InternalSwap(&other->transactionreceipts_);
  signaturelist_.InternalSwap(&other->signaturelist_);
  swap(blockheader_, other->blockheader_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ParallelBlockPB::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace bcos
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::bcos::protocol::ParallelBlockPB* Arena::CreateMaybeMessage< ::bcos::protocol::ParallelBlockPB >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bcos::protocol::ParallelBlockPB >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
