// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransactionReceipt.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_TransactionReceipt_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_TransactionReceipt_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_TransactionReceipt_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_TransactionReceipt_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TransactionReceipt_2eproto;
namespace bcos {
namespace protocol {
class TransactionReceiptPB;
class TransactionReceiptPBDefaultTypeInternal;
extern TransactionReceiptPBDefaultTypeInternal _TransactionReceiptPB_default_instance_;
class TransactionReceiptPB_LogEntry;
class TransactionReceiptPB_LogEntryDefaultTypeInternal;
extern TransactionReceiptPB_LogEntryDefaultTypeInternal _TransactionReceiptPB_LogEntry_default_instance_;
}  // namespace protocol
}  // namespace bcos
PROTOBUF_NAMESPACE_OPEN
template<> ::bcos::protocol::TransactionReceiptPB* Arena::CreateMaybeMessage<::bcos::protocol::TransactionReceiptPB>(Arena*);
template<> ::bcos::protocol::TransactionReceiptPB_LogEntry* Arena::CreateMaybeMessage<::bcos::protocol::TransactionReceiptPB_LogEntry>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace bcos {
namespace protocol {

// ===================================================================

class TransactionReceiptPB_LogEntry PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bcos.protocol.TransactionReceiptPB.LogEntry) */ {
 public:
  inline TransactionReceiptPB_LogEntry() : TransactionReceiptPB_LogEntry(nullptr) {}
  virtual ~TransactionReceiptPB_LogEntry();

  TransactionReceiptPB_LogEntry(const TransactionReceiptPB_LogEntry& from);
  TransactionReceiptPB_LogEntry(TransactionReceiptPB_LogEntry&& from) noexcept
    : TransactionReceiptPB_LogEntry() {
    *this = ::std::move(from);
  }

  inline TransactionReceiptPB_LogEntry& operator=(const TransactionReceiptPB_LogEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransactionReceiptPB_LogEntry& operator=(TransactionReceiptPB_LogEntry&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TransactionReceiptPB_LogEntry& default_instance();

  static inline const TransactionReceiptPB_LogEntry* internal_default_instance() {
    return reinterpret_cast<const TransactionReceiptPB_LogEntry*>(
               &_TransactionReceiptPB_LogEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TransactionReceiptPB_LogEntry& a, TransactionReceiptPB_LogEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(TransactionReceiptPB_LogEntry* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransactionReceiptPB_LogEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TransactionReceiptPB_LogEntry* New() const final {
    return CreateMaybeMessage<TransactionReceiptPB_LogEntry>(nullptr);
  }

  TransactionReceiptPB_LogEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TransactionReceiptPB_LogEntry>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TransactionReceiptPB_LogEntry& from);
  void MergeFrom(const TransactionReceiptPB_LogEntry& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TransactionReceiptPB_LogEntry* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bcos.protocol.TransactionReceiptPB.LogEntry";
  }
  protected:
  explicit TransactionReceiptPB_LogEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_TransactionReceipt_2eproto);
    return ::descriptor_table_TransactionReceipt_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAddressFieldNumber = 1,
    kTopicsFieldNumber = 2,
    kDataFieldNumber = 3,
  };
  // bytes address = 1;
  void clear_address();
  const std::string& address() const;
  void set_address(const std::string& value);
  void set_address(std::string&& value);
  void set_address(const char* value);
  void set_address(const void* value, size_t size);
  std::string* mutable_address();
  std::string* release_address();
  void set_allocated_address(std::string* address);
  private:
  const std::string& _internal_address() const;
  void _internal_set_address(const std::string& value);
  std::string* _internal_mutable_address();
  public:

  // bytes topics = 2;
  void clear_topics();
  const std::string& topics() const;
  void set_topics(const std::string& value);
  void set_topics(std::string&& value);
  void set_topics(const char* value);
  void set_topics(const void* value, size_t size);
  std::string* mutable_topics();
  std::string* release_topics();
  void set_allocated_topics(std::string* topics);
  private:
  const std::string& _internal_topics() const;
  void _internal_set_topics(const std::string& value);
  std::string* _internal_mutable_topics();
  public:

  // bytes data = 3;
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // @@protoc_insertion_point(class_scope:bcos.protocol.TransactionReceiptPB.LogEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr address_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr topics_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_TransactionReceipt_2eproto;
};
// -------------------------------------------------------------------

class TransactionReceiptPB PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bcos.protocol.TransactionReceiptPB) */ {
 public:
  inline TransactionReceiptPB() : TransactionReceiptPB(nullptr) {}
  virtual ~TransactionReceiptPB();

  TransactionReceiptPB(const TransactionReceiptPB& from);
  TransactionReceiptPB(TransactionReceiptPB&& from) noexcept
    : TransactionReceiptPB() {
    *this = ::std::move(from);
  }

  inline TransactionReceiptPB& operator=(const TransactionReceiptPB& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransactionReceiptPB& operator=(TransactionReceiptPB&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TransactionReceiptPB& default_instance();

  static inline const TransactionReceiptPB* internal_default_instance() {
    return reinterpret_cast<const TransactionReceiptPB*>(
               &_TransactionReceiptPB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TransactionReceiptPB& a, TransactionReceiptPB& b) {
    a.Swap(&b);
  }
  inline void Swap(TransactionReceiptPB* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransactionReceiptPB* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TransactionReceiptPB* New() const final {
    return CreateMaybeMessage<TransactionReceiptPB>(nullptr);
  }

  TransactionReceiptPB* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TransactionReceiptPB>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TransactionReceiptPB& from);
  void MergeFrom(const TransactionReceiptPB& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TransactionReceiptPB* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bcos.protocol.TransactionReceiptPB";
  }
  protected:
  explicit TransactionReceiptPB(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_TransactionReceipt_2eproto);
    return ::descriptor_table_TransactionReceipt_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef TransactionReceiptPB_LogEntry LogEntry;

  // accessors -------------------------------------------------------

  enum : int {
    kStateRootFieldNumber = 2,
    kGasUsedFieldNumber = 3,
    kContractAddressFieldNumber = 4,
    kBloomFieldNumber = 5,
    kOutputBytesFieldNumber = 7,
    kLogEntriesFieldNumber = 8,
    kVersionFieldNumber = 1,
    kStatusFieldNumber = 6,
  };
  // bytes stateRoot = 2;
  void clear_stateroot();
  const std::string& stateroot() const;
  void set_stateroot(const std::string& value);
  void set_stateroot(std::string&& value);
  void set_stateroot(const char* value);
  void set_stateroot(const void* value, size_t size);
  std::string* mutable_stateroot();
  std::string* release_stateroot();
  void set_allocated_stateroot(std::string* stateroot);
  private:
  const std::string& _internal_stateroot() const;
  void _internal_set_stateroot(const std::string& value);
  std::string* _internal_mutable_stateroot();
  public:

  // string gasUsed = 3;
  void clear_gasused();
  const std::string& gasused() const;
  void set_gasused(const std::string& value);
  void set_gasused(std::string&& value);
  void set_gasused(const char* value);
  void set_gasused(const char* value, size_t size);
  std::string* mutable_gasused();
  std::string* release_gasused();
  void set_allocated_gasused(std::string* gasused);
  private:
  const std::string& _internal_gasused() const;
  void _internal_set_gasused(const std::string& value);
  std::string* _internal_mutable_gasused();
  public:

  // bytes contractAddress = 4;
  void clear_contractaddress();
  const std::string& contractaddress() const;
  void set_contractaddress(const std::string& value);
  void set_contractaddress(std::string&& value);
  void set_contractaddress(const char* value);
  void set_contractaddress(const void* value, size_t size);
  std::string* mutable_contractaddress();
  std::string* release_contractaddress();
  void set_allocated_contractaddress(std::string* contractaddress);
  private:
  const std::string& _internal_contractaddress() const;
  void _internal_set_contractaddress(const std::string& value);
  std::string* _internal_mutable_contractaddress();
  public:

  // bytes bloom = 5;
  void clear_bloom();
  const std::string& bloom() const;
  void set_bloom(const std::string& value);
  void set_bloom(std::string&& value);
  void set_bloom(const char* value);
  void set_bloom(const void* value, size_t size);
  std::string* mutable_bloom();
  std::string* release_bloom();
  void set_allocated_bloom(std::string* bloom);
  private:
  const std::string& _internal_bloom() const;
  void _internal_set_bloom(const std::string& value);
  std::string* _internal_mutable_bloom();
  public:

  // bytes outputBytes = 7;
  void clear_outputbytes();
  const std::string& outputbytes() const;
  void set_outputbytes(const std::string& value);
  void set_outputbytes(std::string&& value);
  void set_outputbytes(const char* value);
  void set_outputbytes(const void* value, size_t size);
  std::string* mutable_outputbytes();
  std::string* release_outputbytes();
  void set_allocated_outputbytes(std::string* outputbytes);
  private:
  const std::string& _internal_outputbytes() const;
  void _internal_set_outputbytes(const std::string& value);
  std::string* _internal_mutable_outputbytes();
  public:

  // .bcos.protocol.TransactionReceiptPB.LogEntry logEntries = 8;
  bool has_logentries() const;
  private:
  bool _internal_has_logentries() const;
  public:
  void clear_logentries();
  const ::bcos::protocol::TransactionReceiptPB_LogEntry& logentries() const;
  ::bcos::protocol::TransactionReceiptPB_LogEntry* release_logentries();
  ::bcos::protocol::TransactionReceiptPB_LogEntry* mutable_logentries();
  void set_allocated_logentries(::bcos::protocol::TransactionReceiptPB_LogEntry* logentries);
  private:
  const ::bcos::protocol::TransactionReceiptPB_LogEntry& _internal_logentries() const;
  ::bcos::protocol::TransactionReceiptPB_LogEntry* _internal_mutable_logentries();
  public:
  void unsafe_arena_set_allocated_logentries(
      ::bcos::protocol::TransactionReceiptPB_LogEntry* logentries);
  ::bcos::protocol::TransactionReceiptPB_LogEntry* unsafe_arena_release_logentries();

  // int32 version = 1;
  void clear_version();
  ::PROTOBUF_NAMESPACE_ID::int32 version() const;
  void set_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_version() const;
  void _internal_set_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 status = 6;
  void clear_status();
  ::PROTOBUF_NAMESPACE_ID::int32 status() const;
  void set_status(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_status() const;
  void _internal_set_status(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:bcos.protocol.TransactionReceiptPB)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stateroot_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr gasused_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr contractaddress_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bloom_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr outputbytes_;
  ::bcos::protocol::TransactionReceiptPB_LogEntry* logentries_;
  ::PROTOBUF_NAMESPACE_ID::int32 version_;
  ::PROTOBUF_NAMESPACE_ID::int32 status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_TransactionReceipt_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TransactionReceiptPB_LogEntry

// bytes address = 1;
inline void TransactionReceiptPB_LogEntry::clear_address() {
  address_.ClearToEmpty();
}
inline const std::string& TransactionReceiptPB_LogEntry::address() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionReceiptPB.LogEntry.address)
  return _internal_address();
}
inline void TransactionReceiptPB_LogEntry::set_address(const std::string& value) {
  _internal_set_address(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionReceiptPB.LogEntry.address)
}
inline std::string* TransactionReceiptPB_LogEntry::mutable_address() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionReceiptPB.LogEntry.address)
  return _internal_mutable_address();
}
inline const std::string& TransactionReceiptPB_LogEntry::_internal_address() const {
  return address_.Get();
}
inline void TransactionReceiptPB_LogEntry::_internal_set_address(const std::string& value) {
  
  address_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionReceiptPB_LogEntry::set_address(std::string&& value) {
  
  address_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionReceiptPB.LogEntry.address)
}
inline void TransactionReceiptPB_LogEntry::set_address(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  address_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionReceiptPB.LogEntry.address)
}
inline void TransactionReceiptPB_LogEntry::set_address(const void* value,
    size_t size) {
  
  address_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionReceiptPB.LogEntry.address)
}
inline std::string* TransactionReceiptPB_LogEntry::_internal_mutable_address() {
  
  return address_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionReceiptPB_LogEntry::release_address() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionReceiptPB.LogEntry.address)
  return address_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionReceiptPB_LogEntry::set_allocated_address(std::string* address) {
  if (address != nullptr) {
    
  } else {
    
  }
  address_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), address,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionReceiptPB.LogEntry.address)
}

// bytes topics = 2;
inline void TransactionReceiptPB_LogEntry::clear_topics() {
  topics_.ClearToEmpty();
}
inline const std::string& TransactionReceiptPB_LogEntry::topics() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionReceiptPB.LogEntry.topics)
  return _internal_topics();
}
inline void TransactionReceiptPB_LogEntry::set_topics(const std::string& value) {
  _internal_set_topics(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionReceiptPB.LogEntry.topics)
}
inline std::string* TransactionReceiptPB_LogEntry::mutable_topics() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionReceiptPB.LogEntry.topics)
  return _internal_mutable_topics();
}
inline const std::string& TransactionReceiptPB_LogEntry::_internal_topics() const {
  return topics_.Get();
}
inline void TransactionReceiptPB_LogEntry::_internal_set_topics(const std::string& value) {
  
  topics_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionReceiptPB_LogEntry::set_topics(std::string&& value) {
  
  topics_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionReceiptPB.LogEntry.topics)
}
inline void TransactionReceiptPB_LogEntry::set_topics(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  topics_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionReceiptPB.LogEntry.topics)
}
inline void TransactionReceiptPB_LogEntry::set_topics(const void* value,
    size_t size) {
  
  topics_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionReceiptPB.LogEntry.topics)
}
inline std::string* TransactionReceiptPB_LogEntry::_internal_mutable_topics() {
  
  return topics_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionReceiptPB_LogEntry::release_topics() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionReceiptPB.LogEntry.topics)
  return topics_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionReceiptPB_LogEntry::set_allocated_topics(std::string* topics) {
  if (topics != nullptr) {
    
  } else {
    
  }
  topics_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), topics,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionReceiptPB.LogEntry.topics)
}

// bytes data = 3;
inline void TransactionReceiptPB_LogEntry::clear_data() {
  data_.ClearToEmpty();
}
inline const std::string& TransactionReceiptPB_LogEntry::data() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionReceiptPB.LogEntry.data)
  return _internal_data();
}
inline void TransactionReceiptPB_LogEntry::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionReceiptPB.LogEntry.data)
}
inline std::string* TransactionReceiptPB_LogEntry::mutable_data() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionReceiptPB.LogEntry.data)
  return _internal_mutable_data();
}
inline const std::string& TransactionReceiptPB_LogEntry::_internal_data() const {
  return data_.Get();
}
inline void TransactionReceiptPB_LogEntry::_internal_set_data(const std::string& value) {
  
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionReceiptPB_LogEntry::set_data(std::string&& value) {
  
  data_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionReceiptPB.LogEntry.data)
}
inline void TransactionReceiptPB_LogEntry::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionReceiptPB.LogEntry.data)
}
inline void TransactionReceiptPB_LogEntry::set_data(const void* value,
    size_t size) {
  
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionReceiptPB.LogEntry.data)
}
inline std::string* TransactionReceiptPB_LogEntry::_internal_mutable_data() {
  
  return data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionReceiptPB_LogEntry::release_data() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionReceiptPB.LogEntry.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionReceiptPB_LogEntry::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionReceiptPB.LogEntry.data)
}

// -------------------------------------------------------------------

// TransactionReceiptPB

// int32 version = 1;
inline void TransactionReceiptPB::clear_version() {
  version_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TransactionReceiptPB::_internal_version() const {
  return version_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TransactionReceiptPB::version() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionReceiptPB.version)
  return _internal_version();
}
inline void TransactionReceiptPB::_internal_set_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  version_ = value;
}
inline void TransactionReceiptPB::set_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionReceiptPB.version)
}

// bytes stateRoot = 2;
inline void TransactionReceiptPB::clear_stateroot() {
  stateroot_.ClearToEmpty();
}
inline const std::string& TransactionReceiptPB::stateroot() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionReceiptPB.stateRoot)
  return _internal_stateroot();
}
inline void TransactionReceiptPB::set_stateroot(const std::string& value) {
  _internal_set_stateroot(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionReceiptPB.stateRoot)
}
inline std::string* TransactionReceiptPB::mutable_stateroot() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionReceiptPB.stateRoot)
  return _internal_mutable_stateroot();
}
inline const std::string& TransactionReceiptPB::_internal_stateroot() const {
  return stateroot_.Get();
}
inline void TransactionReceiptPB::_internal_set_stateroot(const std::string& value) {
  
  stateroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionReceiptPB::set_stateroot(std::string&& value) {
  
  stateroot_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionReceiptPB.stateRoot)
}
inline void TransactionReceiptPB::set_stateroot(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  stateroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionReceiptPB.stateRoot)
}
inline void TransactionReceiptPB::set_stateroot(const void* value,
    size_t size) {
  
  stateroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionReceiptPB.stateRoot)
}
inline std::string* TransactionReceiptPB::_internal_mutable_stateroot() {
  
  return stateroot_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionReceiptPB::release_stateroot() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionReceiptPB.stateRoot)
  return stateroot_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionReceiptPB::set_allocated_stateroot(std::string* stateroot) {
  if (stateroot != nullptr) {
    
  } else {
    
  }
  stateroot_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), stateroot,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionReceiptPB.stateRoot)
}

// string gasUsed = 3;
inline void TransactionReceiptPB::clear_gasused() {
  gasused_.ClearToEmpty();
}
inline const std::string& TransactionReceiptPB::gasused() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionReceiptPB.gasUsed)
  return _internal_gasused();
}
inline void TransactionReceiptPB::set_gasused(const std::string& value) {
  _internal_set_gasused(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionReceiptPB.gasUsed)
}
inline std::string* TransactionReceiptPB::mutable_gasused() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionReceiptPB.gasUsed)
  return _internal_mutable_gasused();
}
inline const std::string& TransactionReceiptPB::_internal_gasused() const {
  return gasused_.Get();
}
inline void TransactionReceiptPB::_internal_set_gasused(const std::string& value) {
  
  gasused_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionReceiptPB::set_gasused(std::string&& value) {
  
  gasused_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionReceiptPB.gasUsed)
}
inline void TransactionReceiptPB::set_gasused(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  gasused_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionReceiptPB.gasUsed)
}
inline void TransactionReceiptPB::set_gasused(const char* value,
    size_t size) {
  
  gasused_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionReceiptPB.gasUsed)
}
inline std::string* TransactionReceiptPB::_internal_mutable_gasused() {
  
  return gasused_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionReceiptPB::release_gasused() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionReceiptPB.gasUsed)
  return gasused_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionReceiptPB::set_allocated_gasused(std::string* gasused) {
  if (gasused != nullptr) {
    
  } else {
    
  }
  gasused_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), gasused,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionReceiptPB.gasUsed)
}

// bytes contractAddress = 4;
inline void TransactionReceiptPB::clear_contractaddress() {
  contractaddress_.ClearToEmpty();
}
inline const std::string& TransactionReceiptPB::contractaddress() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionReceiptPB.contractAddress)
  return _internal_contractaddress();
}
inline void TransactionReceiptPB::set_contractaddress(const std::string& value) {
  _internal_set_contractaddress(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionReceiptPB.contractAddress)
}
inline std::string* TransactionReceiptPB::mutable_contractaddress() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionReceiptPB.contractAddress)
  return _internal_mutable_contractaddress();
}
inline const std::string& TransactionReceiptPB::_internal_contractaddress() const {
  return contractaddress_.Get();
}
inline void TransactionReceiptPB::_internal_set_contractaddress(const std::string& value) {
  
  contractaddress_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionReceiptPB::set_contractaddress(std::string&& value) {
  
  contractaddress_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionReceiptPB.contractAddress)
}
inline void TransactionReceiptPB::set_contractaddress(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  contractaddress_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionReceiptPB.contractAddress)
}
inline void TransactionReceiptPB::set_contractaddress(const void* value,
    size_t size) {
  
  contractaddress_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionReceiptPB.contractAddress)
}
inline std::string* TransactionReceiptPB::_internal_mutable_contractaddress() {
  
  return contractaddress_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionReceiptPB::release_contractaddress() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionReceiptPB.contractAddress)
  return contractaddress_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionReceiptPB::set_allocated_contractaddress(std::string* contractaddress) {
  if (contractaddress != nullptr) {
    
  } else {
    
  }
  contractaddress_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), contractaddress,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionReceiptPB.contractAddress)
}

// bytes bloom = 5;
inline void TransactionReceiptPB::clear_bloom() {
  bloom_.ClearToEmpty();
}
inline const std::string& TransactionReceiptPB::bloom() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionReceiptPB.bloom)
  return _internal_bloom();
}
inline void TransactionReceiptPB::set_bloom(const std::string& value) {
  _internal_set_bloom(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionReceiptPB.bloom)
}
inline std::string* TransactionReceiptPB::mutable_bloom() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionReceiptPB.bloom)
  return _internal_mutable_bloom();
}
inline const std::string& TransactionReceiptPB::_internal_bloom() const {
  return bloom_.Get();
}
inline void TransactionReceiptPB::_internal_set_bloom(const std::string& value) {
  
  bloom_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionReceiptPB::set_bloom(std::string&& value) {
  
  bloom_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionReceiptPB.bloom)
}
inline void TransactionReceiptPB::set_bloom(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  bloom_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionReceiptPB.bloom)
}
inline void TransactionReceiptPB::set_bloom(const void* value,
    size_t size) {
  
  bloom_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionReceiptPB.bloom)
}
inline std::string* TransactionReceiptPB::_internal_mutable_bloom() {
  
  return bloom_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionReceiptPB::release_bloom() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionReceiptPB.bloom)
  return bloom_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionReceiptPB::set_allocated_bloom(std::string* bloom) {
  if (bloom != nullptr) {
    
  } else {
    
  }
  bloom_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), bloom,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionReceiptPB.bloom)
}

// int32 status = 6;
inline void TransactionReceiptPB::clear_status() {
  status_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TransactionReceiptPB::_internal_status() const {
  return status_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TransactionReceiptPB::status() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionReceiptPB.status)
  return _internal_status();
}
inline void TransactionReceiptPB::_internal_set_status(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  status_ = value;
}
inline void TransactionReceiptPB::set_status(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionReceiptPB.status)
}

// bytes outputBytes = 7;
inline void TransactionReceiptPB::clear_outputbytes() {
  outputbytes_.ClearToEmpty();
}
inline const std::string& TransactionReceiptPB::outputbytes() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionReceiptPB.outputBytes)
  return _internal_outputbytes();
}
inline void TransactionReceiptPB::set_outputbytes(const std::string& value) {
  _internal_set_outputbytes(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionReceiptPB.outputBytes)
}
inline std::string* TransactionReceiptPB::mutable_outputbytes() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionReceiptPB.outputBytes)
  return _internal_mutable_outputbytes();
}
inline const std::string& TransactionReceiptPB::_internal_outputbytes() const {
  return outputbytes_.Get();
}
inline void TransactionReceiptPB::_internal_set_outputbytes(const std::string& value) {
  
  outputbytes_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionReceiptPB::set_outputbytes(std::string&& value) {
  
  outputbytes_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionReceiptPB.outputBytes)
}
inline void TransactionReceiptPB::set_outputbytes(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  outputbytes_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionReceiptPB.outputBytes)
}
inline void TransactionReceiptPB::set_outputbytes(const void* value,
    size_t size) {
  
  outputbytes_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionReceiptPB.outputBytes)
}
inline std::string* TransactionReceiptPB::_internal_mutable_outputbytes() {
  
  return outputbytes_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionReceiptPB::release_outputbytes() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionReceiptPB.outputBytes)
  return outputbytes_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionReceiptPB::set_allocated_outputbytes(std::string* outputbytes) {
  if (outputbytes != nullptr) {
    
  } else {
    
  }
  outputbytes_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), outputbytes,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionReceiptPB.outputBytes)
}

// .bcos.protocol.TransactionReceiptPB.LogEntry logEntries = 8;
inline bool TransactionReceiptPB::_internal_has_logentries() const {
  return this != internal_default_instance() && logentries_ != nullptr;
}
inline bool TransactionReceiptPB::has_logentries() const {
  return _internal_has_logentries();
}
inline void TransactionReceiptPB::clear_logentries() {
  if (GetArena() == nullptr && logentries_ != nullptr) {
    delete logentries_;
  }
  logentries_ = nullptr;
}
inline const ::bcos::protocol::TransactionReceiptPB_LogEntry& TransactionReceiptPB::_internal_logentries() const {
  const ::bcos::protocol::TransactionReceiptPB_LogEntry* p = logentries_;
  return p != nullptr ? *p : reinterpret_cast<const ::bcos::protocol::TransactionReceiptPB_LogEntry&>(
      ::bcos::protocol::_TransactionReceiptPB_LogEntry_default_instance_);
}
inline const ::bcos::protocol::TransactionReceiptPB_LogEntry& TransactionReceiptPB::logentries() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionReceiptPB.logEntries)
  return _internal_logentries();
}
inline void TransactionReceiptPB::unsafe_arena_set_allocated_logentries(
    ::bcos::protocol::TransactionReceiptPB_LogEntry* logentries) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(logentries_);
  }
  logentries_ = logentries;
  if (logentries) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:bcos.protocol.TransactionReceiptPB.logEntries)
}
inline ::bcos::protocol::TransactionReceiptPB_LogEntry* TransactionReceiptPB::release_logentries() {
  
  ::bcos::protocol::TransactionReceiptPB_LogEntry* temp = logentries_;
  logentries_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::bcos::protocol::TransactionReceiptPB_LogEntry* TransactionReceiptPB::unsafe_arena_release_logentries() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionReceiptPB.logEntries)
  
  ::bcos::protocol::TransactionReceiptPB_LogEntry* temp = logentries_;
  logentries_ = nullptr;
  return temp;
}
inline ::bcos::protocol::TransactionReceiptPB_LogEntry* TransactionReceiptPB::_internal_mutable_logentries() {
  
  if (logentries_ == nullptr) {
    auto* p = CreateMaybeMessage<::bcos::protocol::TransactionReceiptPB_LogEntry>(GetArena());
    logentries_ = p;
  }
  return logentries_;
}
inline ::bcos::protocol::TransactionReceiptPB_LogEntry* TransactionReceiptPB::mutable_logentries() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionReceiptPB.logEntries)
  return _internal_mutable_logentries();
}
inline void TransactionReceiptPB::set_allocated_logentries(::bcos::protocol::TransactionReceiptPB_LogEntry* logentries) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete logentries_;
  }
  if (logentries) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(logentries);
    if (message_arena != submessage_arena) {
      logentries = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, logentries, submessage_arena);
    }
    
  } else {
    
  }
  logentries_ = logentries;
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionReceiptPB.logEntries)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace bcos

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_TransactionReceipt_2eproto
