// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transaction.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Transaction_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Transaction_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Transaction_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Transaction_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Transaction_2eproto;
namespace bcos {
namespace protocol {
class SignaturePB;
class SignaturePBDefaultTypeInternal;
extern SignaturePBDefaultTypeInternal _SignaturePB_default_instance_;
class TransactionPB;
class TransactionPBDefaultTypeInternal;
extern TransactionPBDefaultTypeInternal _TransactionPB_default_instance_;
class TransactionPB_ExtendDataMapEntry_DoNotUse;
class TransactionPB_ExtendDataMapEntry_DoNotUseDefaultTypeInternal;
extern TransactionPB_ExtendDataMapEntry_DoNotUseDefaultTypeInternal _TransactionPB_ExtendDataMapEntry_DoNotUse_default_instance_;
class TransactionPB_ExtendDataType;
class TransactionPB_ExtendDataTypeDefaultTypeInternal;
extern TransactionPB_ExtendDataTypeDefaultTypeInternal _TransactionPB_ExtendDataType_default_instance_;
}  // namespace protocol
}  // namespace bcos
PROTOBUF_NAMESPACE_OPEN
template<> ::bcos::protocol::SignaturePB* Arena::CreateMaybeMessage<::bcos::protocol::SignaturePB>(Arena*);
template<> ::bcos::protocol::TransactionPB* Arena::CreateMaybeMessage<::bcos::protocol::TransactionPB>(Arena*);
template<> ::bcos::protocol::TransactionPB_ExtendDataMapEntry_DoNotUse* Arena::CreateMaybeMessage<::bcos::protocol::TransactionPB_ExtendDataMapEntry_DoNotUse>(Arena*);
template<> ::bcos::protocol::TransactionPB_ExtendDataType* Arena::CreateMaybeMessage<::bcos::protocol::TransactionPB_ExtendDataType>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace bcos {
namespace protocol {

// ===================================================================

class SignaturePB PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bcos.protocol.SignaturePB) */ {
 public:
  inline SignaturePB() : SignaturePB(nullptr) {}
  virtual ~SignaturePB();

  SignaturePB(const SignaturePB& from);
  SignaturePB(SignaturePB&& from) noexcept
    : SignaturePB() {
    *this = ::std::move(from);
  }

  inline SignaturePB& operator=(const SignaturePB& from) {
    CopyFrom(from);
    return *this;
  }
  inline SignaturePB& operator=(SignaturePB&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SignaturePB& default_instance();

  static inline const SignaturePB* internal_default_instance() {
    return reinterpret_cast<const SignaturePB*>(
               &_SignaturePB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SignaturePB& a, SignaturePB& b) {
    a.Swap(&b);
  }
  inline void Swap(SignaturePB* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SignaturePB* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SignaturePB* New() const final {
    return CreateMaybeMessage<SignaturePB>(nullptr);
  }

  SignaturePB* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SignaturePB>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SignaturePB& from);
  void MergeFrom(const SignaturePB& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SignaturePB* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bcos.protocol.SignaturePB";
  }
  protected:
  explicit SignaturePB(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Transaction_2eproto);
    return ::descriptor_table_Transaction_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRFieldNumber = 1,
    kSFieldNumber = 2,
    kPubFieldNumber = 4,
    kVFieldNumber = 3,
  };
  // bytes r = 1;
  void clear_r();
  const std::string& r() const;
  void set_r(const std::string& value);
  void set_r(std::string&& value);
  void set_r(const char* value);
  void set_r(const void* value, size_t size);
  std::string* mutable_r();
  std::string* release_r();
  void set_allocated_r(std::string* r);
  private:
  const std::string& _internal_r() const;
  void _internal_set_r(const std::string& value);
  std::string* _internal_mutable_r();
  public:

  // bytes s = 2;
  void clear_s();
  const std::string& s() const;
  void set_s(const std::string& value);
  void set_s(std::string&& value);
  void set_s(const char* value);
  void set_s(const void* value, size_t size);
  std::string* mutable_s();
  std::string* release_s();
  void set_allocated_s(std::string* s);
  private:
  const std::string& _internal_s() const;
  void _internal_set_s(const std::string& value);
  std::string* _internal_mutable_s();
  public:

  // bytes pub = 4;
  void clear_pub();
  const std::string& pub() const;
  void set_pub(const std::string& value);
  void set_pub(std::string&& value);
  void set_pub(const char* value);
  void set_pub(const void* value, size_t size);
  std::string* mutable_pub();
  std::string* release_pub();
  void set_allocated_pub(std::string* pub);
  private:
  const std::string& _internal_pub() const;
  void _internal_set_pub(const std::string& value);
  std::string* _internal_mutable_pub();
  public:

  // int32 v = 3;
  void clear_v();
  ::PROTOBUF_NAMESPACE_ID::int32 v() const;
  void set_v(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_v() const;
  void _internal_set_v(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:bcos.protocol.SignaturePB)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr r_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr s_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pub_;
  ::PROTOBUF_NAMESPACE_ID::int32 v_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Transaction_2eproto;
};
// -------------------------------------------------------------------

class TransactionPB_ExtendDataType PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bcos.protocol.TransactionPB.ExtendDataType) */ {
 public:
  inline TransactionPB_ExtendDataType() : TransactionPB_ExtendDataType(nullptr) {}
  virtual ~TransactionPB_ExtendDataType();

  TransactionPB_ExtendDataType(const TransactionPB_ExtendDataType& from);
  TransactionPB_ExtendDataType(TransactionPB_ExtendDataType&& from) noexcept
    : TransactionPB_ExtendDataType() {
    *this = ::std::move(from);
  }

  inline TransactionPB_ExtendDataType& operator=(const TransactionPB_ExtendDataType& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransactionPB_ExtendDataType& operator=(TransactionPB_ExtendDataType&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TransactionPB_ExtendDataType& default_instance();

  static inline const TransactionPB_ExtendDataType* internal_default_instance() {
    return reinterpret_cast<const TransactionPB_ExtendDataType*>(
               &_TransactionPB_ExtendDataType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TransactionPB_ExtendDataType& a, TransactionPB_ExtendDataType& b) {
    a.Swap(&b);
  }
  inline void Swap(TransactionPB_ExtendDataType* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransactionPB_ExtendDataType* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TransactionPB_ExtendDataType* New() const final {
    return CreateMaybeMessage<TransactionPB_ExtendDataType>(nullptr);
  }

  TransactionPB_ExtendDataType* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TransactionPB_ExtendDataType>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TransactionPB_ExtendDataType& from);
  void MergeFrom(const TransactionPB_ExtendDataType& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TransactionPB_ExtendDataType* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bcos.protocol.TransactionPB.ExtendDataType";
  }
  protected:
  explicit TransactionPB_ExtendDataType(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Transaction_2eproto);
    return ::descriptor_table_Transaction_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFlagFieldNumber = 1,
    kExtendDataFieldNumber = 2,
  };
  // string flag = 1;
  void clear_flag();
  const std::string& flag() const;
  void set_flag(const std::string& value);
  void set_flag(std::string&& value);
  void set_flag(const char* value);
  void set_flag(const char* value, size_t size);
  std::string* mutable_flag();
  std::string* release_flag();
  void set_allocated_flag(std::string* flag);
  private:
  const std::string& _internal_flag() const;
  void _internal_set_flag(const std::string& value);
  std::string* _internal_mutable_flag();
  public:

  // string extendData = 2;
  void clear_extenddata();
  const std::string& extenddata() const;
  void set_extenddata(const std::string& value);
  void set_extenddata(std::string&& value);
  void set_extenddata(const char* value);
  void set_extenddata(const char* value, size_t size);
  std::string* mutable_extenddata();
  std::string* release_extenddata();
  void set_allocated_extenddata(std::string* extenddata);
  private:
  const std::string& _internal_extenddata() const;
  void _internal_set_extenddata(const std::string& value);
  std::string* _internal_mutable_extenddata();
  public:

  // @@protoc_insertion_point(class_scope:bcos.protocol.TransactionPB.ExtendDataType)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr flag_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr extenddata_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Transaction_2eproto;
};
// -------------------------------------------------------------------

class TransactionPB_ExtendDataMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TransactionPB_ExtendDataMapEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TransactionPB_ExtendDataMapEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  TransactionPB_ExtendDataMapEntry_DoNotUse();
  explicit TransactionPB_ExtendDataMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const TransactionPB_ExtendDataMapEntry_DoNotUse& other);
  static const TransactionPB_ExtendDataMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const TransactionPB_ExtendDataMapEntry_DoNotUse*>(&_TransactionPB_ExtendDataMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Transaction_2eproto);
    return ::descriptor_table_Transaction_2eproto.file_level_metadata[2];
  }

  public:
};

// -------------------------------------------------------------------

class TransactionPB PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bcos.protocol.TransactionPB) */ {
 public:
  inline TransactionPB() : TransactionPB(nullptr) {}
  virtual ~TransactionPB();

  TransactionPB(const TransactionPB& from);
  TransactionPB(TransactionPB&& from) noexcept
    : TransactionPB() {
    *this = ::std::move(from);
  }

  inline TransactionPB& operator=(const TransactionPB& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransactionPB& operator=(TransactionPB&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TransactionPB& default_instance();

  static inline const TransactionPB* internal_default_instance() {
    return reinterpret_cast<const TransactionPB*>(
               &_TransactionPB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(TransactionPB& a, TransactionPB& b) {
    a.Swap(&b);
  }
  inline void Swap(TransactionPB* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransactionPB* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TransactionPB* New() const final {
    return CreateMaybeMessage<TransactionPB>(nullptr);
  }

  TransactionPB* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TransactionPB>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TransactionPB& from);
  void MergeFrom(const TransactionPB& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TransactionPB* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bcos.protocol.TransactionPB";
  }
  protected:
  explicit TransactionPB(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Transaction_2eproto);
    return ::descriptor_table_Transaction_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef TransactionPB_ExtendDataType ExtendDataType;

  // accessors -------------------------------------------------------

  enum : int {
    kExtendDataMapFieldNumber = 11,
    kNonceFieldNumber = 4,
    kGasPriceFieldNumber = 6,
    kGasFieldNumber = 7,
    kInputdataFieldNumber = 9,
    kReceiveAddressFieldNumber = 10,
    kImportTimeFieldNumber = 12,
    kSignatureDataFieldNumber = 8,
    kChainIdFieldNumber = 2,
    kGroupIdFieldNumber = 3,
    kBlockLimitFieldNumber = 5,
    kVersionFieldNumber = 1,
  };
  // map<int32, .bcos.protocol.TransactionPB.ExtendDataType> extendDataMap = 11;
  int extenddatamap_size() const;
  private:
  int _internal_extenddatamap_size() const;
  public:
  void clear_extenddatamap();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType >&
      _internal_extenddatamap() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType >*
      _internal_mutable_extenddatamap();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType >&
      extenddatamap() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType >*
      mutable_extenddatamap();

  // string nonce = 4;
  void clear_nonce();
  const std::string& nonce() const;
  void set_nonce(const std::string& value);
  void set_nonce(std::string&& value);
  void set_nonce(const char* value);
  void set_nonce(const char* value, size_t size);
  std::string* mutable_nonce();
  std::string* release_nonce();
  void set_allocated_nonce(std::string* nonce);
  private:
  const std::string& _internal_nonce() const;
  void _internal_set_nonce(const std::string& value);
  std::string* _internal_mutable_nonce();
  public:

  // string gasPrice = 6;
  void clear_gasprice();
  const std::string& gasprice() const;
  void set_gasprice(const std::string& value);
  void set_gasprice(std::string&& value);
  void set_gasprice(const char* value);
  void set_gasprice(const char* value, size_t size);
  std::string* mutable_gasprice();
  std::string* release_gasprice();
  void set_allocated_gasprice(std::string* gasprice);
  private:
  const std::string& _internal_gasprice() const;
  void _internal_set_gasprice(const std::string& value);
  std::string* _internal_mutable_gasprice();
  public:

  // string gas = 7;
  void clear_gas();
  const std::string& gas() const;
  void set_gas(const std::string& value);
  void set_gas(std::string&& value);
  void set_gas(const char* value);
  void set_gas(const char* value, size_t size);
  std::string* mutable_gas();
  std::string* release_gas();
  void set_allocated_gas(std::string* gas);
  private:
  const std::string& _internal_gas() const;
  void _internal_set_gas(const std::string& value);
  std::string* _internal_mutable_gas();
  public:

  // bytes inputdata = 9;
  void clear_inputdata();
  const std::string& inputdata() const;
  void set_inputdata(const std::string& value);
  void set_inputdata(std::string&& value);
  void set_inputdata(const char* value);
  void set_inputdata(const void* value, size_t size);
  std::string* mutable_inputdata();
  std::string* release_inputdata();
  void set_allocated_inputdata(std::string* inputdata);
  private:
  const std::string& _internal_inputdata() const;
  void _internal_set_inputdata(const std::string& value);
  std::string* _internal_mutable_inputdata();
  public:

  // bytes receiveAddress = 10;
  void clear_receiveaddress();
  const std::string& receiveaddress() const;
  void set_receiveaddress(const std::string& value);
  void set_receiveaddress(std::string&& value);
  void set_receiveaddress(const char* value);
  void set_receiveaddress(const void* value, size_t size);
  std::string* mutable_receiveaddress();
  std::string* release_receiveaddress();
  void set_allocated_receiveaddress(std::string* receiveaddress);
  private:
  const std::string& _internal_receiveaddress() const;
  void _internal_set_receiveaddress(const std::string& value);
  std::string* _internal_mutable_receiveaddress();
  public:

  // string importTime = 12;
  void clear_importtime();
  const std::string& importtime() const;
  void set_importtime(const std::string& value);
  void set_importtime(std::string&& value);
  void set_importtime(const char* value);
  void set_importtime(const char* value, size_t size);
  std::string* mutable_importtime();
  std::string* release_importtime();
  void set_allocated_importtime(std::string* importtime);
  private:
  const std::string& _internal_importtime() const;
  void _internal_set_importtime(const std::string& value);
  std::string* _internal_mutable_importtime();
  public:

  // .bcos.protocol.SignaturePB signatureData = 8;
  bool has_signaturedata() const;
  private:
  bool _internal_has_signaturedata() const;
  public:
  void clear_signaturedata();
  const ::bcos::protocol::SignaturePB& signaturedata() const;
  ::bcos::protocol::SignaturePB* release_signaturedata();
  ::bcos::protocol::SignaturePB* mutable_signaturedata();
  void set_allocated_signaturedata(::bcos::protocol::SignaturePB* signaturedata);
  private:
  const ::bcos::protocol::SignaturePB& _internal_signaturedata() const;
  ::bcos::protocol::SignaturePB* _internal_mutable_signaturedata();
  public:
  void unsafe_arena_set_allocated_signaturedata(
      ::bcos::protocol::SignaturePB* signaturedata);
  ::bcos::protocol::SignaturePB* unsafe_arena_release_signaturedata();

  // int64 chainId = 2;
  void clear_chainid();
  ::PROTOBUF_NAMESPACE_ID::int64 chainid() const;
  void set_chainid(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_chainid() const;
  void _internal_set_chainid(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 groupId = 3;
  void clear_groupid();
  ::PROTOBUF_NAMESPACE_ID::int64 groupid() const;
  void set_groupid(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_groupid() const;
  void _internal_set_groupid(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 blockLimit = 5;
  void clear_blocklimit();
  ::PROTOBUF_NAMESPACE_ID::int64 blocklimit() const;
  void set_blocklimit(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_blocklimit() const;
  void _internal_set_blocklimit(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 version = 1;
  void clear_version();
  ::PROTOBUF_NAMESPACE_ID::int32 version() const;
  void set_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_version() const;
  void _internal_set_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:bcos.protocol.TransactionPB)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      TransactionPB_ExtendDataMapEntry_DoNotUse,
      ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> extenddatamap_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nonce_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr gasprice_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr gas_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr inputdata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr receiveaddress_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr importtime_;
  ::bcos::protocol::SignaturePB* signaturedata_;
  ::PROTOBUF_NAMESPACE_ID::int64 chainid_;
  ::PROTOBUF_NAMESPACE_ID::int64 groupid_;
  ::PROTOBUF_NAMESPACE_ID::int64 blocklimit_;
  ::PROTOBUF_NAMESPACE_ID::int32 version_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Transaction_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SignaturePB

// bytes r = 1;
inline void SignaturePB::clear_r() {
  r_.ClearToEmpty();
}
inline const std::string& SignaturePB::r() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.SignaturePB.r)
  return _internal_r();
}
inline void SignaturePB::set_r(const std::string& value) {
  _internal_set_r(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.SignaturePB.r)
}
inline std::string* SignaturePB::mutable_r() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.SignaturePB.r)
  return _internal_mutable_r();
}
inline const std::string& SignaturePB::_internal_r() const {
  return r_.Get();
}
inline void SignaturePB::_internal_set_r(const std::string& value) {
  
  r_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void SignaturePB::set_r(std::string&& value) {
  
  r_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.SignaturePB.r)
}
inline void SignaturePB::set_r(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  r_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.SignaturePB.r)
}
inline void SignaturePB::set_r(const void* value,
    size_t size) {
  
  r_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.SignaturePB.r)
}
inline std::string* SignaturePB::_internal_mutable_r() {
  
  return r_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* SignaturePB::release_r() {
  // @@protoc_insertion_point(field_release:bcos.protocol.SignaturePB.r)
  return r_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SignaturePB::set_allocated_r(std::string* r) {
  if (r != nullptr) {
    
  } else {
    
  }
  r_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), r,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.SignaturePB.r)
}

// bytes s = 2;
inline void SignaturePB::clear_s() {
  s_.ClearToEmpty();
}
inline const std::string& SignaturePB::s() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.SignaturePB.s)
  return _internal_s();
}
inline void SignaturePB::set_s(const std::string& value) {
  _internal_set_s(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.SignaturePB.s)
}
inline std::string* SignaturePB::mutable_s() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.SignaturePB.s)
  return _internal_mutable_s();
}
inline const std::string& SignaturePB::_internal_s() const {
  return s_.Get();
}
inline void SignaturePB::_internal_set_s(const std::string& value) {
  
  s_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void SignaturePB::set_s(std::string&& value) {
  
  s_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.SignaturePB.s)
}
inline void SignaturePB::set_s(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  s_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.SignaturePB.s)
}
inline void SignaturePB::set_s(const void* value,
    size_t size) {
  
  s_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.SignaturePB.s)
}
inline std::string* SignaturePB::_internal_mutable_s() {
  
  return s_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* SignaturePB::release_s() {
  // @@protoc_insertion_point(field_release:bcos.protocol.SignaturePB.s)
  return s_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SignaturePB::set_allocated_s(std::string* s) {
  if (s != nullptr) {
    
  } else {
    
  }
  s_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), s,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.SignaturePB.s)
}

// int32 v = 3;
inline void SignaturePB::clear_v() {
  v_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SignaturePB::_internal_v() const {
  return v_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SignaturePB::v() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.SignaturePB.v)
  return _internal_v();
}
inline void SignaturePB::_internal_set_v(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  v_ = value;
}
inline void SignaturePB::set_v(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_v(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.SignaturePB.v)
}

// bytes pub = 4;
inline void SignaturePB::clear_pub() {
  pub_.ClearToEmpty();
}
inline const std::string& SignaturePB::pub() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.SignaturePB.pub)
  return _internal_pub();
}
inline void SignaturePB::set_pub(const std::string& value) {
  _internal_set_pub(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.SignaturePB.pub)
}
inline std::string* SignaturePB::mutable_pub() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.SignaturePB.pub)
  return _internal_mutable_pub();
}
inline const std::string& SignaturePB::_internal_pub() const {
  return pub_.Get();
}
inline void SignaturePB::_internal_set_pub(const std::string& value) {
  
  pub_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void SignaturePB::set_pub(std::string&& value) {
  
  pub_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.SignaturePB.pub)
}
inline void SignaturePB::set_pub(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  pub_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.SignaturePB.pub)
}
inline void SignaturePB::set_pub(const void* value,
    size_t size) {
  
  pub_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.SignaturePB.pub)
}
inline std::string* SignaturePB::_internal_mutable_pub() {
  
  return pub_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* SignaturePB::release_pub() {
  // @@protoc_insertion_point(field_release:bcos.protocol.SignaturePB.pub)
  return pub_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SignaturePB::set_allocated_pub(std::string* pub) {
  if (pub != nullptr) {
    
  } else {
    
  }
  pub_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), pub,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.SignaturePB.pub)
}

// -------------------------------------------------------------------

// TransactionPB_ExtendDataType

// string flag = 1;
inline void TransactionPB_ExtendDataType::clear_flag() {
  flag_.ClearToEmpty();
}
inline const std::string& TransactionPB_ExtendDataType::flag() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionPB.ExtendDataType.flag)
  return _internal_flag();
}
inline void TransactionPB_ExtendDataType::set_flag(const std::string& value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionPB.ExtendDataType.flag)
}
inline std::string* TransactionPB_ExtendDataType::mutable_flag() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionPB.ExtendDataType.flag)
  return _internal_mutable_flag();
}
inline const std::string& TransactionPB_ExtendDataType::_internal_flag() const {
  return flag_.Get();
}
inline void TransactionPB_ExtendDataType::_internal_set_flag(const std::string& value) {
  
  flag_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionPB_ExtendDataType::set_flag(std::string&& value) {
  
  flag_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionPB.ExtendDataType.flag)
}
inline void TransactionPB_ExtendDataType::set_flag(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  flag_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionPB.ExtendDataType.flag)
}
inline void TransactionPB_ExtendDataType::set_flag(const char* value,
    size_t size) {
  
  flag_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionPB.ExtendDataType.flag)
}
inline std::string* TransactionPB_ExtendDataType::_internal_mutable_flag() {
  
  return flag_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionPB_ExtendDataType::release_flag() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionPB.ExtendDataType.flag)
  return flag_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionPB_ExtendDataType::set_allocated_flag(std::string* flag) {
  if (flag != nullptr) {
    
  } else {
    
  }
  flag_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), flag,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionPB.ExtendDataType.flag)
}

// string extendData = 2;
inline void TransactionPB_ExtendDataType::clear_extenddata() {
  extenddata_.ClearToEmpty();
}
inline const std::string& TransactionPB_ExtendDataType::extenddata() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionPB.ExtendDataType.extendData)
  return _internal_extenddata();
}
inline void TransactionPB_ExtendDataType::set_extenddata(const std::string& value) {
  _internal_set_extenddata(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionPB.ExtendDataType.extendData)
}
inline std::string* TransactionPB_ExtendDataType::mutable_extenddata() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionPB.ExtendDataType.extendData)
  return _internal_mutable_extenddata();
}
inline const std::string& TransactionPB_ExtendDataType::_internal_extenddata() const {
  return extenddata_.Get();
}
inline void TransactionPB_ExtendDataType::_internal_set_extenddata(const std::string& value) {
  
  extenddata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionPB_ExtendDataType::set_extenddata(std::string&& value) {
  
  extenddata_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionPB.ExtendDataType.extendData)
}
inline void TransactionPB_ExtendDataType::set_extenddata(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  extenddata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionPB.ExtendDataType.extendData)
}
inline void TransactionPB_ExtendDataType::set_extenddata(const char* value,
    size_t size) {
  
  extenddata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionPB.ExtendDataType.extendData)
}
inline std::string* TransactionPB_ExtendDataType::_internal_mutable_extenddata() {
  
  return extenddata_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionPB_ExtendDataType::release_extenddata() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionPB.ExtendDataType.extendData)
  return extenddata_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionPB_ExtendDataType::set_allocated_extenddata(std::string* extenddata) {
  if (extenddata != nullptr) {
    
  } else {
    
  }
  extenddata_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), extenddata,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionPB.ExtendDataType.extendData)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// TransactionPB

// int32 version = 1;
inline void TransactionPB::clear_version() {
  version_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TransactionPB::_internal_version() const {
  return version_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TransactionPB::version() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionPB.version)
  return _internal_version();
}
inline void TransactionPB::_internal_set_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  version_ = value;
}
inline void TransactionPB::set_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionPB.version)
}

// int64 chainId = 2;
inline void TransactionPB::clear_chainid() {
  chainid_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TransactionPB::_internal_chainid() const {
  return chainid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TransactionPB::chainid() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionPB.chainId)
  return _internal_chainid();
}
inline void TransactionPB::_internal_set_chainid(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  chainid_ = value;
}
inline void TransactionPB::set_chainid(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_chainid(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionPB.chainId)
}

// int64 groupId = 3;
inline void TransactionPB::clear_groupid() {
  groupid_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TransactionPB::_internal_groupid() const {
  return groupid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TransactionPB::groupid() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionPB.groupId)
  return _internal_groupid();
}
inline void TransactionPB::_internal_set_groupid(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  groupid_ = value;
}
inline void TransactionPB::set_groupid(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_groupid(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionPB.groupId)
}

// string nonce = 4;
inline void TransactionPB::clear_nonce() {
  nonce_.ClearToEmpty();
}
inline const std::string& TransactionPB::nonce() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionPB.nonce)
  return _internal_nonce();
}
inline void TransactionPB::set_nonce(const std::string& value) {
  _internal_set_nonce(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionPB.nonce)
}
inline std::string* TransactionPB::mutable_nonce() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionPB.nonce)
  return _internal_mutable_nonce();
}
inline const std::string& TransactionPB::_internal_nonce() const {
  return nonce_.Get();
}
inline void TransactionPB::_internal_set_nonce(const std::string& value) {
  
  nonce_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionPB::set_nonce(std::string&& value) {
  
  nonce_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionPB.nonce)
}
inline void TransactionPB::set_nonce(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  nonce_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionPB.nonce)
}
inline void TransactionPB::set_nonce(const char* value,
    size_t size) {
  
  nonce_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionPB.nonce)
}
inline std::string* TransactionPB::_internal_mutable_nonce() {
  
  return nonce_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionPB::release_nonce() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionPB.nonce)
  return nonce_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionPB::set_allocated_nonce(std::string* nonce) {
  if (nonce != nullptr) {
    
  } else {
    
  }
  nonce_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), nonce,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionPB.nonce)
}

// int64 blockLimit = 5;
inline void TransactionPB::clear_blocklimit() {
  blocklimit_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TransactionPB::_internal_blocklimit() const {
  return blocklimit_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TransactionPB::blocklimit() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionPB.blockLimit)
  return _internal_blocklimit();
}
inline void TransactionPB::_internal_set_blocklimit(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  blocklimit_ = value;
}
inline void TransactionPB::set_blocklimit(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_blocklimit(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionPB.blockLimit)
}

// string gasPrice = 6;
inline void TransactionPB::clear_gasprice() {
  gasprice_.ClearToEmpty();
}
inline const std::string& TransactionPB::gasprice() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionPB.gasPrice)
  return _internal_gasprice();
}
inline void TransactionPB::set_gasprice(const std::string& value) {
  _internal_set_gasprice(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionPB.gasPrice)
}
inline std::string* TransactionPB::mutable_gasprice() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionPB.gasPrice)
  return _internal_mutable_gasprice();
}
inline const std::string& TransactionPB::_internal_gasprice() const {
  return gasprice_.Get();
}
inline void TransactionPB::_internal_set_gasprice(const std::string& value) {
  
  gasprice_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionPB::set_gasprice(std::string&& value) {
  
  gasprice_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionPB.gasPrice)
}
inline void TransactionPB::set_gasprice(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  gasprice_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionPB.gasPrice)
}
inline void TransactionPB::set_gasprice(const char* value,
    size_t size) {
  
  gasprice_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionPB.gasPrice)
}
inline std::string* TransactionPB::_internal_mutable_gasprice() {
  
  return gasprice_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionPB::release_gasprice() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionPB.gasPrice)
  return gasprice_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionPB::set_allocated_gasprice(std::string* gasprice) {
  if (gasprice != nullptr) {
    
  } else {
    
  }
  gasprice_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), gasprice,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionPB.gasPrice)
}

// string gas = 7;
inline void TransactionPB::clear_gas() {
  gas_.ClearToEmpty();
}
inline const std::string& TransactionPB::gas() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionPB.gas)
  return _internal_gas();
}
inline void TransactionPB::set_gas(const std::string& value) {
  _internal_set_gas(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionPB.gas)
}
inline std::string* TransactionPB::mutable_gas() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionPB.gas)
  return _internal_mutable_gas();
}
inline const std::string& TransactionPB::_internal_gas() const {
  return gas_.Get();
}
inline void TransactionPB::_internal_set_gas(const std::string& value) {
  
  gas_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionPB::set_gas(std::string&& value) {
  
  gas_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionPB.gas)
}
inline void TransactionPB::set_gas(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  gas_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionPB.gas)
}
inline void TransactionPB::set_gas(const char* value,
    size_t size) {
  
  gas_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionPB.gas)
}
inline std::string* TransactionPB::_internal_mutable_gas() {
  
  return gas_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionPB::release_gas() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionPB.gas)
  return gas_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionPB::set_allocated_gas(std::string* gas) {
  if (gas != nullptr) {
    
  } else {
    
  }
  gas_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), gas,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionPB.gas)
}

// .bcos.protocol.SignaturePB signatureData = 8;
inline bool TransactionPB::_internal_has_signaturedata() const {
  return this != internal_default_instance() && signaturedata_ != nullptr;
}
inline bool TransactionPB::has_signaturedata() const {
  return _internal_has_signaturedata();
}
inline void TransactionPB::clear_signaturedata() {
  if (GetArena() == nullptr && signaturedata_ != nullptr) {
    delete signaturedata_;
  }
  signaturedata_ = nullptr;
}
inline const ::bcos::protocol::SignaturePB& TransactionPB::_internal_signaturedata() const {
  const ::bcos::protocol::SignaturePB* p = signaturedata_;
  return p != nullptr ? *p : reinterpret_cast<const ::bcos::protocol::SignaturePB&>(
      ::bcos::protocol::_SignaturePB_default_instance_);
}
inline const ::bcos::protocol::SignaturePB& TransactionPB::signaturedata() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionPB.signatureData)
  return _internal_signaturedata();
}
inline void TransactionPB::unsafe_arena_set_allocated_signaturedata(
    ::bcos::protocol::SignaturePB* signaturedata) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(signaturedata_);
  }
  signaturedata_ = signaturedata;
  if (signaturedata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:bcos.protocol.TransactionPB.signatureData)
}
inline ::bcos::protocol::SignaturePB* TransactionPB::release_signaturedata() {
  
  ::bcos::protocol::SignaturePB* temp = signaturedata_;
  signaturedata_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::bcos::protocol::SignaturePB* TransactionPB::unsafe_arena_release_signaturedata() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionPB.signatureData)
  
  ::bcos::protocol::SignaturePB* temp = signaturedata_;
  signaturedata_ = nullptr;
  return temp;
}
inline ::bcos::protocol::SignaturePB* TransactionPB::_internal_mutable_signaturedata() {
  
  if (signaturedata_ == nullptr) {
    auto* p = CreateMaybeMessage<::bcos::protocol::SignaturePB>(GetArena());
    signaturedata_ = p;
  }
  return signaturedata_;
}
inline ::bcos::protocol::SignaturePB* TransactionPB::mutable_signaturedata() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionPB.signatureData)
  return _internal_mutable_signaturedata();
}
inline void TransactionPB::set_allocated_signaturedata(::bcos::protocol::SignaturePB* signaturedata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete signaturedata_;
  }
  if (signaturedata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(signaturedata);
    if (message_arena != submessage_arena) {
      signaturedata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, signaturedata, submessage_arena);
    }
    
  } else {
    
  }
  signaturedata_ = signaturedata;
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionPB.signatureData)
}

// bytes inputdata = 9;
inline void TransactionPB::clear_inputdata() {
  inputdata_.ClearToEmpty();
}
inline const std::string& TransactionPB::inputdata() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionPB.inputdata)
  return _internal_inputdata();
}
inline void TransactionPB::set_inputdata(const std::string& value) {
  _internal_set_inputdata(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionPB.inputdata)
}
inline std::string* TransactionPB::mutable_inputdata() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionPB.inputdata)
  return _internal_mutable_inputdata();
}
inline const std::string& TransactionPB::_internal_inputdata() const {
  return inputdata_.Get();
}
inline void TransactionPB::_internal_set_inputdata(const std::string& value) {
  
  inputdata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionPB::set_inputdata(std::string&& value) {
  
  inputdata_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionPB.inputdata)
}
inline void TransactionPB::set_inputdata(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  inputdata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionPB.inputdata)
}
inline void TransactionPB::set_inputdata(const void* value,
    size_t size) {
  
  inputdata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionPB.inputdata)
}
inline std::string* TransactionPB::_internal_mutable_inputdata() {
  
  return inputdata_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionPB::release_inputdata() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionPB.inputdata)
  return inputdata_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionPB::set_allocated_inputdata(std::string* inputdata) {
  if (inputdata != nullptr) {
    
  } else {
    
  }
  inputdata_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), inputdata,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionPB.inputdata)
}

// bytes receiveAddress = 10;
inline void TransactionPB::clear_receiveaddress() {
  receiveaddress_.ClearToEmpty();
}
inline const std::string& TransactionPB::receiveaddress() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionPB.receiveAddress)
  return _internal_receiveaddress();
}
inline void TransactionPB::set_receiveaddress(const std::string& value) {
  _internal_set_receiveaddress(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionPB.receiveAddress)
}
inline std::string* TransactionPB::mutable_receiveaddress() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionPB.receiveAddress)
  return _internal_mutable_receiveaddress();
}
inline const std::string& TransactionPB::_internal_receiveaddress() const {
  return receiveaddress_.Get();
}
inline void TransactionPB::_internal_set_receiveaddress(const std::string& value) {
  
  receiveaddress_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionPB::set_receiveaddress(std::string&& value) {
  
  receiveaddress_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionPB.receiveAddress)
}
inline void TransactionPB::set_receiveaddress(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  receiveaddress_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionPB.receiveAddress)
}
inline void TransactionPB::set_receiveaddress(const void* value,
    size_t size) {
  
  receiveaddress_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionPB.receiveAddress)
}
inline std::string* TransactionPB::_internal_mutable_receiveaddress() {
  
  return receiveaddress_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionPB::release_receiveaddress() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionPB.receiveAddress)
  return receiveaddress_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionPB::set_allocated_receiveaddress(std::string* receiveaddress) {
  if (receiveaddress != nullptr) {
    
  } else {
    
  }
  receiveaddress_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), receiveaddress,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionPB.receiveAddress)
}

// map<int32, .bcos.protocol.TransactionPB.ExtendDataType> extendDataMap = 11;
inline int TransactionPB::_internal_extenddatamap_size() const {
  return extenddatamap_.size();
}
inline int TransactionPB::extenddatamap_size() const {
  return _internal_extenddatamap_size();
}
inline void TransactionPB::clear_extenddatamap() {
  extenddatamap_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType >&
TransactionPB::_internal_extenddatamap() const {
  return extenddatamap_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType >&
TransactionPB::extenddatamap() const {
  // @@protoc_insertion_point(field_map:bcos.protocol.TransactionPB.extendDataMap)
  return _internal_extenddatamap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType >*
TransactionPB::_internal_mutable_extenddatamap() {
  return extenddatamap_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType >*
TransactionPB::mutable_extenddatamap() {
  // @@protoc_insertion_point(field_mutable_map:bcos.protocol.TransactionPB.extendDataMap)
  return _internal_mutable_extenddatamap();
}

// string importTime = 12;
inline void TransactionPB::clear_importtime() {
  importtime_.ClearToEmpty();
}
inline const std::string& TransactionPB::importtime() const {
  // @@protoc_insertion_point(field_get:bcos.protocol.TransactionPB.importTime)
  return _internal_importtime();
}
inline void TransactionPB::set_importtime(const std::string& value) {
  _internal_set_importtime(value);
  // @@protoc_insertion_point(field_set:bcos.protocol.TransactionPB.importTime)
}
inline std::string* TransactionPB::mutable_importtime() {
  // @@protoc_insertion_point(field_mutable:bcos.protocol.TransactionPB.importTime)
  return _internal_mutable_importtime();
}
inline const std::string& TransactionPB::_internal_importtime() const {
  return importtime_.Get();
}
inline void TransactionPB::_internal_set_importtime(const std::string& value) {
  
  importtime_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TransactionPB::set_importtime(std::string&& value) {
  
  importtime_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bcos.protocol.TransactionPB.importTime)
}
inline void TransactionPB::set_importtime(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  importtime_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:bcos.protocol.TransactionPB.importTime)
}
inline void TransactionPB::set_importtime(const char* value,
    size_t size) {
  
  importtime_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bcos.protocol.TransactionPB.importTime)
}
inline std::string* TransactionPB::_internal_mutable_importtime() {
  
  return importtime_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TransactionPB::release_importtime() {
  // @@protoc_insertion_point(field_release:bcos.protocol.TransactionPB.importTime)
  return importtime_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TransactionPB::set_allocated_importtime(std::string* importtime) {
  if (importtime != nullptr) {
    
  } else {
    
  }
  importtime_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), importtime,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bcos.protocol.TransactionPB.importTime)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace bcos

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Transaction_2eproto
