// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransactionReceipt.proto

#include "TransactionReceipt.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_TransactionReceipt_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TransactionReceiptPB_LogEntry_TransactionReceipt_2eproto;
namespace bcos {
namespace protocol {
class TransactionReceiptPB_LogEntryDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TransactionReceiptPB_LogEntry> _instance;
} _TransactionReceiptPB_LogEntry_default_instance_;
class TransactionReceiptPBDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TransactionReceiptPB> _instance;
} _TransactionReceiptPB_default_instance_;
}  // namespace protocol
}  // namespace bcos
static void InitDefaultsscc_info_TransactionReceiptPB_TransactionReceipt_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bcos::protocol::_TransactionReceiptPB_default_instance_;
    new (ptr) ::bcos::protocol::TransactionReceiptPB();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_TransactionReceiptPB_TransactionReceipt_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_TransactionReceiptPB_TransactionReceipt_2eproto}, {
      &scc_info_TransactionReceiptPB_LogEntry_TransactionReceipt_2eproto.base,}};

static void InitDefaultsscc_info_TransactionReceiptPB_LogEntry_TransactionReceipt_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bcos::protocol::_TransactionReceiptPB_LogEntry_default_instance_;
    new (ptr) ::bcos::protocol::TransactionReceiptPB_LogEntry();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TransactionReceiptPB_LogEntry_TransactionReceipt_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_TransactionReceiptPB_LogEntry_TransactionReceipt_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_TransactionReceipt_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_TransactionReceipt_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_TransactionReceipt_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_TransactionReceipt_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionReceiptPB_LogEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionReceiptPB_LogEntry, address_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionReceiptPB_LogEntry, topics_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionReceiptPB_LogEntry, data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionReceiptPB, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionReceiptPB, version_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionReceiptPB, stateroot_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionReceiptPB, gasused_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionReceiptPB, contractaddress_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionReceiptPB, bloom_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionReceiptPB, status_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionReceiptPB, outputbytes_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionReceiptPB, logentries_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::bcos::protocol::TransactionReceiptPB_LogEntry)},
  { 8, -1, sizeof(::bcos::protocol::TransactionReceiptPB)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bcos::protocol::_TransactionReceiptPB_LogEntry_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bcos::protocol::_TransactionReceiptPB_default_instance_),
};

const char descriptor_table_protodef_TransactionReceipt_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030TransactionReceipt.proto\022\rbcos.protoco"
  "l\"\225\002\n\024TransactionReceiptPB\022\017\n\007version\030\001 "
  "\001(\005\022\021\n\tstateRoot\030\002 \001(\014\022\017\n\007gasUsed\030\003 \001(\t\022"
  "\027\n\017contractAddress\030\004 \001(\014\022\r\n\005bloom\030\005 \001(\014\022"
  "\016\n\006status\030\006 \001(\005\022\023\n\013outputBytes\030\007 \001(\014\022@\n\n"
  "logEntries\030\010 \001(\0132,.bcos.protocol.Transac"
  "tionReceiptPB.LogEntry\0329\n\010LogEntry\022\017\n\007ad"
  "dress\030\001 \001(\014\022\016\n\006topics\030\002 \001(\014\022\014\n\004data\030\003 \001("
  "\014b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_TransactionReceipt_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_TransactionReceipt_2eproto_sccs[2] = {
  &scc_info_TransactionReceiptPB_TransactionReceipt_2eproto.base,
  &scc_info_TransactionReceiptPB_LogEntry_TransactionReceipt_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_TransactionReceipt_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TransactionReceipt_2eproto = {
  false, false, descriptor_table_protodef_TransactionReceipt_2eproto, "TransactionReceipt.proto", 329,
  &descriptor_table_TransactionReceipt_2eproto_once, descriptor_table_TransactionReceipt_2eproto_sccs, descriptor_table_TransactionReceipt_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_TransactionReceipt_2eproto::offsets,
  file_level_metadata_TransactionReceipt_2eproto, 2, file_level_enum_descriptors_TransactionReceipt_2eproto, file_level_service_descriptors_TransactionReceipt_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_TransactionReceipt_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_TransactionReceipt_2eproto)), true);
namespace bcos {
namespace protocol {

// ===================================================================

class TransactionReceiptPB_LogEntry::_Internal {
 public:
};

TransactionReceiptPB_LogEntry::TransactionReceiptPB_LogEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:bcos.protocol.TransactionReceiptPB.LogEntry)
}
TransactionReceiptPB_LogEntry::TransactionReceiptPB_LogEntry(const TransactionReceiptPB_LogEntry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_address().empty()) {
    address_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_address(), 
      GetArena());
  }
  topics_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_topics().empty()) {
    topics_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_topics(), 
      GetArena());
  }
  data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_data().empty()) {
    data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_data(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:bcos.protocol.TransactionReceiptPB.LogEntry)
}

void TransactionReceiptPB_LogEntry::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TransactionReceiptPB_LogEntry_TransactionReceipt_2eproto.base);
  address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  topics_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

TransactionReceiptPB_LogEntry::~TransactionReceiptPB_LogEntry() {
  // @@protoc_insertion_point(destructor:bcos.protocol.TransactionReceiptPB.LogEntry)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void TransactionReceiptPB_LogEntry::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  address_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  topics_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  data_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void TransactionReceiptPB_LogEntry::ArenaDtor(void* object) {
  TransactionReceiptPB_LogEntry* _this = reinterpret_cast< TransactionReceiptPB_LogEntry* >(object);
  (void)_this;
}
void TransactionReceiptPB_LogEntry::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TransactionReceiptPB_LogEntry::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TransactionReceiptPB_LogEntry& TransactionReceiptPB_LogEntry::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TransactionReceiptPB_LogEntry_TransactionReceipt_2eproto.base);
  return *internal_default_instance();
}


void TransactionReceiptPB_LogEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:bcos.protocol.TransactionReceiptPB.LogEntry)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  address_.ClearToEmpty();
  topics_.ClearToEmpty();
  data_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransactionReceiptPB_LogEntry::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bytes address = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_address();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes topics = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_topics();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_data();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TransactionReceiptPB_LogEntry::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bcos.protocol.TransactionReceiptPB.LogEntry)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes address = 1;
  if (this->address().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_address(), target);
  }

  // bytes topics = 2;
  if (this->topics().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_topics(), target);
  }

  // bytes data = 3;
  if (this->data().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bcos.protocol.TransactionReceiptPB.LogEntry)
  return target;
}

size_t TransactionReceiptPB_LogEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bcos.protocol.TransactionReceiptPB.LogEntry)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes address = 1;
  if (this->address().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_address());
  }

  // bytes topics = 2;
  if (this->topics().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_topics());
  }

  // bytes data = 3;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TransactionReceiptPB_LogEntry::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bcos.protocol.TransactionReceiptPB.LogEntry)
  GOOGLE_DCHECK_NE(&from, this);
  const TransactionReceiptPB_LogEntry* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TransactionReceiptPB_LogEntry>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bcos.protocol.TransactionReceiptPB.LogEntry)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bcos.protocol.TransactionReceiptPB.LogEntry)
    MergeFrom(*source);
  }
}

void TransactionReceiptPB_LogEntry::MergeFrom(const TransactionReceiptPB_LogEntry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bcos.protocol.TransactionReceiptPB.LogEntry)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.address().size() > 0) {
    _internal_set_address(from._internal_address());
  }
  if (from.topics().size() > 0) {
    _internal_set_topics(from._internal_topics());
  }
  if (from.data().size() > 0) {
    _internal_set_data(from._internal_data());
  }
}

void TransactionReceiptPB_LogEntry::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bcos.protocol.TransactionReceiptPB.LogEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TransactionReceiptPB_LogEntry::CopyFrom(const TransactionReceiptPB_LogEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bcos.protocol.TransactionReceiptPB.LogEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransactionReceiptPB_LogEntry::IsInitialized() const {
  return true;
}

void TransactionReceiptPB_LogEntry::InternalSwap(TransactionReceiptPB_LogEntry* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  address_.Swap(&other->address_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  topics_.Swap(&other->topics_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  data_.Swap(&other->data_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata TransactionReceiptPB_LogEntry::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class TransactionReceiptPB::_Internal {
 public:
  static const ::bcos::protocol::TransactionReceiptPB_LogEntry& logentries(const TransactionReceiptPB* msg);
};

const ::bcos::protocol::TransactionReceiptPB_LogEntry&
TransactionReceiptPB::_Internal::logentries(const TransactionReceiptPB* msg) {
  return *msg->logentries_;
}
TransactionReceiptPB::TransactionReceiptPB(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:bcos.protocol.TransactionReceiptPB)
}
TransactionReceiptPB::TransactionReceiptPB(const TransactionReceiptPB& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  stateroot_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_stateroot().empty()) {
    stateroot_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_stateroot(), 
      GetArena());
  }
  gasused_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_gasused().empty()) {
    gasused_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_gasused(), 
      GetArena());
  }
  contractaddress_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_contractaddress().empty()) {
    contractaddress_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_contractaddress(), 
      GetArena());
  }
  bloom_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_bloom().empty()) {
    bloom_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_bloom(), 
      GetArena());
  }
  outputbytes_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_outputbytes().empty()) {
    outputbytes_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_outputbytes(), 
      GetArena());
  }
  if (from._internal_has_logentries()) {
    logentries_ = new ::bcos::protocol::TransactionReceiptPB_LogEntry(*from.logentries_);
  } else {
    logentries_ = nullptr;
  }
  ::memcpy(&version_, &from.version_,
    static_cast<size_t>(reinterpret_cast<char*>(&status_) -
    reinterpret_cast<char*>(&version_)) + sizeof(status_));
  // @@protoc_insertion_point(copy_constructor:bcos.protocol.TransactionReceiptPB)
}

void TransactionReceiptPB::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TransactionReceiptPB_TransactionReceipt_2eproto.base);
  stateroot_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  gasused_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  contractaddress_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  bloom_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  outputbytes_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&logentries_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&logentries_)) + sizeof(status_));
}

TransactionReceiptPB::~TransactionReceiptPB() {
  // @@protoc_insertion_point(destructor:bcos.protocol.TransactionReceiptPB)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void TransactionReceiptPB::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  stateroot_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  gasused_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  contractaddress_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  bloom_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  outputbytes_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete logentries_;
}

void TransactionReceiptPB::ArenaDtor(void* object) {
  TransactionReceiptPB* _this = reinterpret_cast< TransactionReceiptPB* >(object);
  (void)_this;
}
void TransactionReceiptPB::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TransactionReceiptPB::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TransactionReceiptPB& TransactionReceiptPB::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TransactionReceiptPB_TransactionReceipt_2eproto.base);
  return *internal_default_instance();
}


void TransactionReceiptPB::Clear() {
// @@protoc_insertion_point(message_clear_start:bcos.protocol.TransactionReceiptPB)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  stateroot_.ClearToEmpty();
  gasused_.ClearToEmpty();
  contractaddress_.ClearToEmpty();
  bloom_.ClearToEmpty();
  outputbytes_.ClearToEmpty();
  if (GetArena() == nullptr && logentries_ != nullptr) {
    delete logentries_;
  }
  logentries_ = nullptr;
  ::memset(&version_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&version_)) + sizeof(status_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransactionReceiptPB::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 version = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes stateRoot = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_stateroot();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string gasUsed = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_gasused();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "bcos.protocol.TransactionReceiptPB.gasUsed"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes contractAddress = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_contractaddress();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes bloom = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_bloom();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 status = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          status_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes outputBytes = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          auto str = _internal_mutable_outputbytes();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .bcos.protocol.TransactionReceiptPB.LogEntry logEntries = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_logentries(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TransactionReceiptPB::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bcos.protocol.TransactionReceiptPB)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 version = 1;
  if (this->version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_version(), target);
  }

  // bytes stateRoot = 2;
  if (this->stateroot().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_stateroot(), target);
  }

  // string gasUsed = 3;
  if (this->gasused().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_gasused().data(), static_cast<int>(this->_internal_gasused().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bcos.protocol.TransactionReceiptPB.gasUsed");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_gasused(), target);
  }

  // bytes contractAddress = 4;
  if (this->contractaddress().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_contractaddress(), target);
  }

  // bytes bloom = 5;
  if (this->bloom().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_bloom(), target);
  }

  // int32 status = 6;
  if (this->status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(6, this->_internal_status(), target);
  }

  // bytes outputBytes = 7;
  if (this->outputbytes().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        7, this->_internal_outputbytes(), target);
  }

  // .bcos.protocol.TransactionReceiptPB.LogEntry logEntries = 8;
  if (this->has_logentries()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        8, _Internal::logentries(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bcos.protocol.TransactionReceiptPB)
  return target;
}

size_t TransactionReceiptPB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bcos.protocol.TransactionReceiptPB)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes stateRoot = 2;
  if (this->stateroot().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_stateroot());
  }

  // string gasUsed = 3;
  if (this->gasused().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_gasused());
  }

  // bytes contractAddress = 4;
  if (this->contractaddress().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_contractaddress());
  }

  // bytes bloom = 5;
  if (this->bloom().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_bloom());
  }

  // bytes outputBytes = 7;
  if (this->outputbytes().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_outputbytes());
  }

  // .bcos.protocol.TransactionReceiptPB.LogEntry logEntries = 8;
  if (this->has_logentries()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *logentries_);
  }

  // int32 version = 1;
  if (this->version() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_version());
  }

  // int32 status = 6;
  if (this->status() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_status());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TransactionReceiptPB::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bcos.protocol.TransactionReceiptPB)
  GOOGLE_DCHECK_NE(&from, this);
  const TransactionReceiptPB* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TransactionReceiptPB>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bcos.protocol.TransactionReceiptPB)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bcos.protocol.TransactionReceiptPB)
    MergeFrom(*source);
  }
}

void TransactionReceiptPB::MergeFrom(const TransactionReceiptPB& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bcos.protocol.TransactionReceiptPB)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.stateroot().size() > 0) {
    _internal_set_stateroot(from._internal_stateroot());
  }
  if (from.gasused().size() > 0) {
    _internal_set_gasused(from._internal_gasused());
  }
  if (from.contractaddress().size() > 0) {
    _internal_set_contractaddress(from._internal_contractaddress());
  }
  if (from.bloom().size() > 0) {
    _internal_set_bloom(from._internal_bloom());
  }
  if (from.outputbytes().size() > 0) {
    _internal_set_outputbytes(from._internal_outputbytes());
  }
  if (from.has_logentries()) {
    _internal_mutable_logentries()->::bcos::protocol::TransactionReceiptPB_LogEntry::MergeFrom(from._internal_logentries());
  }
  if (from.version() != 0) {
    _internal_set_version(from._internal_version());
  }
  if (from.status() != 0) {
    _internal_set_status(from._internal_status());
  }
}

void TransactionReceiptPB::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bcos.protocol.TransactionReceiptPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TransactionReceiptPB::CopyFrom(const TransactionReceiptPB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bcos.protocol.TransactionReceiptPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransactionReceiptPB::IsInitialized() const {
  return true;
}

void TransactionReceiptPB::InternalSwap(TransactionReceiptPB* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  stateroot_.Swap(&other->stateroot_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  gasused_.Swap(&other->gasused_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  contractaddress_.Swap(&other->contractaddress_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  bloom_.Swap(&other->bloom_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  outputbytes_.Swap(&other->outputbytes_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TransactionReceiptPB, status_)
      + sizeof(TransactionReceiptPB::status_)
      - PROTOBUF_FIELD_OFFSET(TransactionReceiptPB, logentries_)>(
          reinterpret_cast<char*>(&logentries_),
          reinterpret_cast<char*>(&other->logentries_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TransactionReceiptPB::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace bcos
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::bcos::protocol::TransactionReceiptPB_LogEntry* Arena::CreateMaybeMessage< ::bcos::protocol::TransactionReceiptPB_LogEntry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bcos::protocol::TransactionReceiptPB_LogEntry >(arena);
}
template<> PROTOBUF_NOINLINE ::bcos::protocol::TransactionReceiptPB* Arena::CreateMaybeMessage< ::bcos::protocol::TransactionReceiptPB >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bcos::protocol::TransactionReceiptPB >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
