// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transaction.proto

#include "Transaction.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_Transaction_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SignaturePB_Transaction_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_Transaction_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_TransactionPB_ExtendDataMapEntry_DoNotUse_Transaction_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_Transaction_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TransactionPB_ExtendDataType_Transaction_2eproto;
namespace bcos {
namespace protocol {
class SignaturePBDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SignaturePB> _instance;
} _SignaturePB_default_instance_;
class TransactionPB_ExtendDataTypeDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TransactionPB_ExtendDataType> _instance;
} _TransactionPB_ExtendDataType_default_instance_;
class TransactionPB_ExtendDataMapEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TransactionPB_ExtendDataMapEntry_DoNotUse> _instance;
} _TransactionPB_ExtendDataMapEntry_DoNotUse_default_instance_;
class TransactionPBDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TransactionPB> _instance;
} _TransactionPB_default_instance_;
}  // namespace protocol
}  // namespace bcos
static void InitDefaultsscc_info_SignaturePB_Transaction_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bcos::protocol::_SignaturePB_default_instance_;
    new (ptr) ::bcos::protocol::SignaturePB();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SignaturePB_Transaction_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SignaturePB_Transaction_2eproto}, {}};

static void InitDefaultsscc_info_TransactionPB_Transaction_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bcos::protocol::_TransactionPB_default_instance_;
    new (ptr) ::bcos::protocol::TransactionPB();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_TransactionPB_Transaction_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_TransactionPB_Transaction_2eproto}, {
      &scc_info_SignaturePB_Transaction_2eproto.base,
      &scc_info_TransactionPB_ExtendDataMapEntry_DoNotUse_Transaction_2eproto.base,}};

static void InitDefaultsscc_info_TransactionPB_ExtendDataMapEntry_DoNotUse_Transaction_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bcos::protocol::_TransactionPB_ExtendDataMapEntry_DoNotUse_default_instance_;
    new (ptr) ::bcos::protocol::TransactionPB_ExtendDataMapEntry_DoNotUse();
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_TransactionPB_ExtendDataMapEntry_DoNotUse_Transaction_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_TransactionPB_ExtendDataMapEntry_DoNotUse_Transaction_2eproto}, {
      &scc_info_TransactionPB_ExtendDataType_Transaction_2eproto.base,}};

static void InitDefaultsscc_info_TransactionPB_ExtendDataType_Transaction_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bcos::protocol::_TransactionPB_ExtendDataType_default_instance_;
    new (ptr) ::bcos::protocol::TransactionPB_ExtendDataType();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TransactionPB_ExtendDataType_Transaction_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_TransactionPB_ExtendDataType_Transaction_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Transaction_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Transaction_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Transaction_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Transaction_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::SignaturePB, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::SignaturePB, r_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::SignaturePB, s_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::SignaturePB, v_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::SignaturePB, pub_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB_ExtendDataType, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB_ExtendDataType, flag_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB_ExtendDataType, extenddata_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB_ExtendDataMapEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB_ExtendDataMapEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB_ExtendDataMapEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB_ExtendDataMapEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB, version_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB, chainid_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB, groupid_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB, nonce_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB, blocklimit_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB, gasprice_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB, gas_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB, signaturedata_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB, inputdata_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB, receiveaddress_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB, extenddatamap_),
  PROTOBUF_FIELD_OFFSET(::bcos::protocol::TransactionPB, importtime_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::bcos::protocol::SignaturePB)},
  { 9, -1, sizeof(::bcos::protocol::TransactionPB_ExtendDataType)},
  { 16, 23, sizeof(::bcos::protocol::TransactionPB_ExtendDataMapEntry_DoNotUse)},
  { 25, -1, sizeof(::bcos::protocol::TransactionPB)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bcos::protocol::_SignaturePB_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bcos::protocol::_TransactionPB_ExtendDataType_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bcos::protocol::_TransactionPB_ExtendDataMapEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bcos::protocol::_TransactionPB_default_instance_),
};

const char descriptor_table_protodef_Transaction_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021Transaction.proto\022\rbcos.protocol\";\n\013Si"
  "gnaturePB\022\t\n\001r\030\001 \001(\014\022\t\n\001s\030\002 \001(\014\022\t\n\001v\030\003 \001"
  "(\005\022\013\n\003pub\030\004 \001(\014\"\325\003\n\rTransactionPB\022\017\n\007ver"
  "sion\030\001 \001(\005\022\017\n\007chainId\030\002 \001(\003\022\017\n\007groupId\030\003"
  " \001(\003\022\r\n\005nonce\030\004 \001(\t\022\022\n\nblockLimit\030\005 \001(\003\022"
  "\020\n\010gasPrice\030\006 \001(\t\022\013\n\003gas\030\007 \001(\t\0221\n\rsignat"
  "ureData\030\010 \001(\0132\032.bcos.protocol.SignatureP"
  "B\022\021\n\tinputdata\030\t \001(\014\022\026\n\016receiveAddress\030\n"
  " \001(\014\022F\n\rextendDataMap\030\013 \003(\0132/.bcos.proto"
  "col.TransactionPB.ExtendDataMapEntry\022\022\n\n"
  "importTime\030\014 \001(\t\0322\n\016ExtendDataType\022\014\n\004fl"
  "ag\030\001 \001(\t\022\022\n\nextendData\030\002 \001(\t\032a\n\022ExtendDa"
  "taMapEntry\022\013\n\003key\030\001 \001(\005\022:\n\005value\030\002 \001(\0132+"
  ".bcos.protocol.TransactionPB.ExtendDataT"
  "ype:\0028\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Transaction_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_Transaction_2eproto_sccs[4] = {
  &scc_info_SignaturePB_Transaction_2eproto.base,
  &scc_info_TransactionPB_Transaction_2eproto.base,
  &scc_info_TransactionPB_ExtendDataMapEntry_DoNotUse_Transaction_2eproto.base,
  &scc_info_TransactionPB_ExtendDataType_Transaction_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Transaction_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Transaction_2eproto = {
  false, false, descriptor_table_protodef_Transaction_2eproto, "Transaction.proto", 575,
  &descriptor_table_Transaction_2eproto_once, descriptor_table_Transaction_2eproto_sccs, descriptor_table_Transaction_2eproto_deps, 4, 0,
  schemas, file_default_instances, TableStruct_Transaction_2eproto::offsets,
  file_level_metadata_Transaction_2eproto, 4, file_level_enum_descriptors_Transaction_2eproto, file_level_service_descriptors_Transaction_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_Transaction_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_Transaction_2eproto)), true);
namespace bcos {
namespace protocol {

// ===================================================================

class SignaturePB::_Internal {
 public:
};

SignaturePB::SignaturePB(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:bcos.protocol.SignaturePB)
}
SignaturePB::SignaturePB(const SignaturePB& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  r_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_r().empty()) {
    r_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_r(), 
      GetArena());
  }
  s_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_s().empty()) {
    s_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_s(), 
      GetArena());
  }
  pub_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_pub().empty()) {
    pub_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_pub(), 
      GetArena());
  }
  v_ = from.v_;
  // @@protoc_insertion_point(copy_constructor:bcos.protocol.SignaturePB)
}

void SignaturePB::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SignaturePB_Transaction_2eproto.base);
  r_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  s_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  pub_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  v_ = 0;
}

SignaturePB::~SignaturePB() {
  // @@protoc_insertion_point(destructor:bcos.protocol.SignaturePB)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SignaturePB::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  r_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  s_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  pub_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SignaturePB::ArenaDtor(void* object) {
  SignaturePB* _this = reinterpret_cast< SignaturePB* >(object);
  (void)_this;
}
void SignaturePB::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SignaturePB::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SignaturePB& SignaturePB::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SignaturePB_Transaction_2eproto.base);
  return *internal_default_instance();
}


void SignaturePB::Clear() {
// @@protoc_insertion_point(message_clear_start:bcos.protocol.SignaturePB)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  r_.ClearToEmpty();
  s_.ClearToEmpty();
  pub_.ClearToEmpty();
  v_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SignaturePB::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bytes r = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_r();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes s = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_s();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 v = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          v_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes pub = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_pub();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SignaturePB::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bcos.protocol.SignaturePB)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes r = 1;
  if (this->r().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_r(), target);
  }

  // bytes s = 2;
  if (this->s().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_s(), target);
  }

  // int32 v = 3;
  if (this->v() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_v(), target);
  }

  // bytes pub = 4;
  if (this->pub().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_pub(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bcos.protocol.SignaturePB)
  return target;
}

size_t SignaturePB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bcos.protocol.SignaturePB)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes r = 1;
  if (this->r().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_r());
  }

  // bytes s = 2;
  if (this->s().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_s());
  }

  // bytes pub = 4;
  if (this->pub().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_pub());
  }

  // int32 v = 3;
  if (this->v() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_v());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SignaturePB::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bcos.protocol.SignaturePB)
  GOOGLE_DCHECK_NE(&from, this);
  const SignaturePB* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SignaturePB>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bcos.protocol.SignaturePB)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bcos.protocol.SignaturePB)
    MergeFrom(*source);
  }
}

void SignaturePB::MergeFrom(const SignaturePB& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bcos.protocol.SignaturePB)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.r().size() > 0) {
    _internal_set_r(from._internal_r());
  }
  if (from.s().size() > 0) {
    _internal_set_s(from._internal_s());
  }
  if (from.pub().size() > 0) {
    _internal_set_pub(from._internal_pub());
  }
  if (from.v() != 0) {
    _internal_set_v(from._internal_v());
  }
}

void SignaturePB::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bcos.protocol.SignaturePB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SignaturePB::CopyFrom(const SignaturePB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bcos.protocol.SignaturePB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SignaturePB::IsInitialized() const {
  return true;
}

void SignaturePB::InternalSwap(SignaturePB* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  r_.Swap(&other->r_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  s_.Swap(&other->s_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  pub_.Swap(&other->pub_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(v_, other->v_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SignaturePB::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class TransactionPB_ExtendDataType::_Internal {
 public:
};

TransactionPB_ExtendDataType::TransactionPB_ExtendDataType(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:bcos.protocol.TransactionPB.ExtendDataType)
}
TransactionPB_ExtendDataType::TransactionPB_ExtendDataType(const TransactionPB_ExtendDataType& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  flag_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_flag().empty()) {
    flag_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_flag(), 
      GetArena());
  }
  extenddata_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_extenddata().empty()) {
    extenddata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_extenddata(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:bcos.protocol.TransactionPB.ExtendDataType)
}

void TransactionPB_ExtendDataType::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TransactionPB_ExtendDataType_Transaction_2eproto.base);
  flag_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  extenddata_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

TransactionPB_ExtendDataType::~TransactionPB_ExtendDataType() {
  // @@protoc_insertion_point(destructor:bcos.protocol.TransactionPB.ExtendDataType)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void TransactionPB_ExtendDataType::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  flag_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  extenddata_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void TransactionPB_ExtendDataType::ArenaDtor(void* object) {
  TransactionPB_ExtendDataType* _this = reinterpret_cast< TransactionPB_ExtendDataType* >(object);
  (void)_this;
}
void TransactionPB_ExtendDataType::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TransactionPB_ExtendDataType::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TransactionPB_ExtendDataType& TransactionPB_ExtendDataType::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TransactionPB_ExtendDataType_Transaction_2eproto.base);
  return *internal_default_instance();
}


void TransactionPB_ExtendDataType::Clear() {
// @@protoc_insertion_point(message_clear_start:bcos.protocol.TransactionPB.ExtendDataType)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  flag_.ClearToEmpty();
  extenddata_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransactionPB_ExtendDataType::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string flag = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_flag();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "bcos.protocol.TransactionPB.ExtendDataType.flag"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string extendData = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_extenddata();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "bcos.protocol.TransactionPB.ExtendDataType.extendData"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TransactionPB_ExtendDataType::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bcos.protocol.TransactionPB.ExtendDataType)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string flag = 1;
  if (this->flag().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_flag().data(), static_cast<int>(this->_internal_flag().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bcos.protocol.TransactionPB.ExtendDataType.flag");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_flag(), target);
  }

  // string extendData = 2;
  if (this->extenddata().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_extenddata().data(), static_cast<int>(this->_internal_extenddata().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bcos.protocol.TransactionPB.ExtendDataType.extendData");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_extenddata(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bcos.protocol.TransactionPB.ExtendDataType)
  return target;
}

size_t TransactionPB_ExtendDataType::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bcos.protocol.TransactionPB.ExtendDataType)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string flag = 1;
  if (this->flag().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_flag());
  }

  // string extendData = 2;
  if (this->extenddata().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_extenddata());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TransactionPB_ExtendDataType::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bcos.protocol.TransactionPB.ExtendDataType)
  GOOGLE_DCHECK_NE(&from, this);
  const TransactionPB_ExtendDataType* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TransactionPB_ExtendDataType>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bcos.protocol.TransactionPB.ExtendDataType)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bcos.protocol.TransactionPB.ExtendDataType)
    MergeFrom(*source);
  }
}

void TransactionPB_ExtendDataType::MergeFrom(const TransactionPB_ExtendDataType& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bcos.protocol.TransactionPB.ExtendDataType)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.flag().size() > 0) {
    _internal_set_flag(from._internal_flag());
  }
  if (from.extenddata().size() > 0) {
    _internal_set_extenddata(from._internal_extenddata());
  }
}

void TransactionPB_ExtendDataType::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bcos.protocol.TransactionPB.ExtendDataType)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TransactionPB_ExtendDataType::CopyFrom(const TransactionPB_ExtendDataType& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bcos.protocol.TransactionPB.ExtendDataType)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransactionPB_ExtendDataType::IsInitialized() const {
  return true;
}

void TransactionPB_ExtendDataType::InternalSwap(TransactionPB_ExtendDataType* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  flag_.Swap(&other->flag_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  extenddata_.Swap(&other->extenddata_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata TransactionPB_ExtendDataType::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

TransactionPB_ExtendDataMapEntry_DoNotUse::TransactionPB_ExtendDataMapEntry_DoNotUse() {}
TransactionPB_ExtendDataMapEntry_DoNotUse::TransactionPB_ExtendDataMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void TransactionPB_ExtendDataMapEntry_DoNotUse::MergeFrom(const TransactionPB_ExtendDataMapEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata TransactionPB_ExtendDataMapEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void TransactionPB_ExtendDataMapEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

class TransactionPB::_Internal {
 public:
  static const ::bcos::protocol::SignaturePB& signaturedata(const TransactionPB* msg);
};

const ::bcos::protocol::SignaturePB&
TransactionPB::_Internal::signaturedata(const TransactionPB* msg) {
  return *msg->signaturedata_;
}
TransactionPB::TransactionPB(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  extenddatamap_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:bcos.protocol.TransactionPB)
}
TransactionPB::TransactionPB(const TransactionPB& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  extenddatamap_.MergeFrom(from.extenddatamap_);
  nonce_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_nonce().empty()) {
    nonce_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_nonce(), 
      GetArena());
  }
  gasprice_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_gasprice().empty()) {
    gasprice_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_gasprice(), 
      GetArena());
  }
  gas_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_gas().empty()) {
    gas_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_gas(), 
      GetArena());
  }
  inputdata_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_inputdata().empty()) {
    inputdata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_inputdata(), 
      GetArena());
  }
  receiveaddress_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_receiveaddress().empty()) {
    receiveaddress_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_receiveaddress(), 
      GetArena());
  }
  importtime_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_importtime().empty()) {
    importtime_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_importtime(), 
      GetArena());
  }
  if (from._internal_has_signaturedata()) {
    signaturedata_ = new ::bcos::protocol::SignaturePB(*from.signaturedata_);
  } else {
    signaturedata_ = nullptr;
  }
  ::memcpy(&chainid_, &from.chainid_,
    static_cast<size_t>(reinterpret_cast<char*>(&version_) -
    reinterpret_cast<char*>(&chainid_)) + sizeof(version_));
  // @@protoc_insertion_point(copy_constructor:bcos.protocol.TransactionPB)
}

void TransactionPB::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TransactionPB_Transaction_2eproto.base);
  nonce_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  gasprice_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  gas_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  inputdata_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  receiveaddress_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  importtime_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&signaturedata_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&version_) -
      reinterpret_cast<char*>(&signaturedata_)) + sizeof(version_));
}

TransactionPB::~TransactionPB() {
  // @@protoc_insertion_point(destructor:bcos.protocol.TransactionPB)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void TransactionPB::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  nonce_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  gasprice_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  gas_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  inputdata_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  receiveaddress_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  importtime_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete signaturedata_;
}

void TransactionPB::ArenaDtor(void* object) {
  TransactionPB* _this = reinterpret_cast< TransactionPB* >(object);
  (void)_this;
}
void TransactionPB::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TransactionPB::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TransactionPB& TransactionPB::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TransactionPB_Transaction_2eproto.base);
  return *internal_default_instance();
}


void TransactionPB::Clear() {
// @@protoc_insertion_point(message_clear_start:bcos.protocol.TransactionPB)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  extenddatamap_.Clear();
  nonce_.ClearToEmpty();
  gasprice_.ClearToEmpty();
  gas_.ClearToEmpty();
  inputdata_.ClearToEmpty();
  receiveaddress_.ClearToEmpty();
  importtime_.ClearToEmpty();
  if (GetArena() == nullptr && signaturedata_ != nullptr) {
    delete signaturedata_;
  }
  signaturedata_ = nullptr;
  ::memset(&chainid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&version_) -
      reinterpret_cast<char*>(&chainid_)) + sizeof(version_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransactionPB::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 version = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 chainId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          chainid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 groupId = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          groupid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string nonce = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_nonce();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "bcos.protocol.TransactionPB.nonce"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 blockLimit = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          blocklimit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string gasPrice = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_gasprice();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "bcos.protocol.TransactionPB.gasPrice"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string gas = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          auto str = _internal_mutable_gas();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "bcos.protocol.TransactionPB.gas"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .bcos.protocol.SignaturePB signatureData = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_signaturedata(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes inputdata = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          auto str = _internal_mutable_inputdata();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes receiveAddress = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          auto str = _internal_mutable_receiveaddress();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // map<int32, .bcos.protocol.TransactionPB.ExtendDataType> extendDataMap = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 90)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&extenddatamap_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<90>(ptr));
        } else goto handle_unusual;
        continue;
      // string importTime = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 98)) {
          auto str = _internal_mutable_importtime();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "bcos.protocol.TransactionPB.importTime"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TransactionPB::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bcos.protocol.TransactionPB)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 version = 1;
  if (this->version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_version(), target);
  }

  // int64 chainId = 2;
  if (this->chainid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(2, this->_internal_chainid(), target);
  }

  // int64 groupId = 3;
  if (this->groupid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(3, this->_internal_groupid(), target);
  }

  // string nonce = 4;
  if (this->nonce().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_nonce().data(), static_cast<int>(this->_internal_nonce().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bcos.protocol.TransactionPB.nonce");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_nonce(), target);
  }

  // int64 blockLimit = 5;
  if (this->blocklimit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(5, this->_internal_blocklimit(), target);
  }

  // string gasPrice = 6;
  if (this->gasprice().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_gasprice().data(), static_cast<int>(this->_internal_gasprice().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bcos.protocol.TransactionPB.gasPrice");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_gasprice(), target);
  }

  // string gas = 7;
  if (this->gas().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_gas().data(), static_cast<int>(this->_internal_gas().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bcos.protocol.TransactionPB.gas");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_gas(), target);
  }

  // .bcos.protocol.SignaturePB signatureData = 8;
  if (this->has_signaturedata()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        8, _Internal::signaturedata(this), target, stream);
  }

  // bytes inputdata = 9;
  if (this->inputdata().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        9, this->_internal_inputdata(), target);
  }

  // bytes receiveAddress = 10;
  if (this->receiveaddress().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        10, this->_internal_receiveaddress(), target);
  }

  // map<int32, .bcos.protocol.TransactionPB.ExtendDataType> extendDataMap = 11;
  if (!this->_internal_extenddatamap().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType >::const_pointer
        ConstPtr;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::SortItem< ::PROTOBUF_NAMESPACE_ID::int32, ConstPtr > SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByFirstField<SortItem> Less;

    if (stream->IsSerializationDeterministic() &&
        this->_internal_extenddatamap().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_extenddatamap().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType >::const_iterator
          it = this->_internal_extenddatamap().begin();
          it != this->_internal_extenddatamap().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = TransactionPB_ExtendDataMapEntry_DoNotUse::Funcs::InternalSerialize(11, items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second, target, stream);
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType >::const_iterator
          it = this->_internal_extenddatamap().begin();
          it != this->_internal_extenddatamap().end(); ++it) {
        target = TransactionPB_ExtendDataMapEntry_DoNotUse::Funcs::InternalSerialize(11, it->first, it->second, target, stream);
      }
    }
  }

  // string importTime = 12;
  if (this->importtime().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_importtime().data(), static_cast<int>(this->_internal_importtime().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bcos.protocol.TransactionPB.importTime");
    target = stream->WriteStringMaybeAliased(
        12, this->_internal_importtime(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bcos.protocol.TransactionPB)
  return target;
}

size_t TransactionPB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bcos.protocol.TransactionPB)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<int32, .bcos.protocol.TransactionPB.ExtendDataType> extendDataMap = 11;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_extenddatamap_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::bcos::protocol::TransactionPB_ExtendDataType >::const_iterator
      it = this->_internal_extenddatamap().begin();
      it != this->_internal_extenddatamap().end(); ++it) {
    total_size += TransactionPB_ExtendDataMapEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // string nonce = 4;
  if (this->nonce().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_nonce());
  }

  // string gasPrice = 6;
  if (this->gasprice().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_gasprice());
  }

  // string gas = 7;
  if (this->gas().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_gas());
  }

  // bytes inputdata = 9;
  if (this->inputdata().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_inputdata());
  }

  // bytes receiveAddress = 10;
  if (this->receiveaddress().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_receiveaddress());
  }

  // string importTime = 12;
  if (this->importtime().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_importtime());
  }

  // .bcos.protocol.SignaturePB signatureData = 8;
  if (this->has_signaturedata()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *signaturedata_);
  }

  // int64 chainId = 2;
  if (this->chainid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_chainid());
  }

  // int64 groupId = 3;
  if (this->groupid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_groupid());
  }

  // int64 blockLimit = 5;
  if (this->blocklimit() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_blocklimit());
  }

  // int32 version = 1;
  if (this->version() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_version());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TransactionPB::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bcos.protocol.TransactionPB)
  GOOGLE_DCHECK_NE(&from, this);
  const TransactionPB* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TransactionPB>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bcos.protocol.TransactionPB)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bcos.protocol.TransactionPB)
    MergeFrom(*source);
  }
}

void TransactionPB::MergeFrom(const TransactionPB& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bcos.protocol.TransactionPB)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  extenddatamap_.MergeFrom(from.extenddatamap_);
  if (from.nonce().size() > 0) {
    _internal_set_nonce(from._internal_nonce());
  }
  if (from.gasprice().size() > 0) {
    _internal_set_gasprice(from._internal_gasprice());
  }
  if (from.gas().size() > 0) {
    _internal_set_gas(from._internal_gas());
  }
  if (from.inputdata().size() > 0) {
    _internal_set_inputdata(from._internal_inputdata());
  }
  if (from.receiveaddress().size() > 0) {
    _internal_set_receiveaddress(from._internal_receiveaddress());
  }
  if (from.importtime().size() > 0) {
    _internal_set_importtime(from._internal_importtime());
  }
  if (from.has_signaturedata()) {
    _internal_mutable_signaturedata()->::bcos::protocol::SignaturePB::MergeFrom(from._internal_signaturedata());
  }
  if (from.chainid() != 0) {
    _internal_set_chainid(from._internal_chainid());
  }
  if (from.groupid() != 0) {
    _internal_set_groupid(from._internal_groupid());
  }
  if (from.blocklimit() != 0) {
    _internal_set_blocklimit(from._internal_blocklimit());
  }
  if (from.version() != 0) {
    _internal_set_version(from._internal_version());
  }
}

void TransactionPB::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bcos.protocol.TransactionPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TransactionPB::CopyFrom(const TransactionPB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bcos.protocol.TransactionPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransactionPB::IsInitialized() const {
  return true;
}

void TransactionPB::InternalSwap(TransactionPB* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  extenddatamap_.Swap(&other->extenddatamap_);
  nonce_.Swap(&other->nonce_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  gasprice_.Swap(&other->gasprice_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  gas_.Swap(&other->gas_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  inputdata_.Swap(&other->inputdata_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  receiveaddress_.Swap(&other->receiveaddress_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  importtime_.Swap(&other->importtime_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TransactionPB, version_)
      + sizeof(TransactionPB::version_)
      - PROTOBUF_FIELD_OFFSET(TransactionPB, signaturedata_)>(
          reinterpret_cast<char*>(&signaturedata_),
          reinterpret_cast<char*>(&other->signaturedata_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TransactionPB::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace bcos
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::bcos::protocol::SignaturePB* Arena::CreateMaybeMessage< ::bcos::protocol::SignaturePB >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bcos::protocol::SignaturePB >(arena);
}
template<> PROTOBUF_NOINLINE ::bcos::protocol::TransactionPB_ExtendDataType* Arena::CreateMaybeMessage< ::bcos::protocol::TransactionPB_ExtendDataType >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bcos::protocol::TransactionPB_ExtendDataType >(arena);
}
template<> PROTOBUF_NOINLINE ::bcos::protocol::TransactionPB_ExtendDataMapEntry_DoNotUse* Arena::CreateMaybeMessage< ::bcos::protocol::TransactionPB_ExtendDataMapEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bcos::protocol::TransactionPB_ExtendDataMapEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::bcos::protocol::TransactionPB* Arena::CreateMaybeMessage< ::bcos::protocol::TransactionPB >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bcos::protocol::TransactionPB >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
